-- ============================================================
-- RabuShinAIGM Rules Build 6.22
-- Crafting / Harvesting
-- Migration 56
-- Requires Solo active-player resolver (Build 6.17+) and inventory system.
-- ============================================================
BEGIN;

CREATE TABLE IF NOT EXISTS public.discord_crafting_recipes
(
    recipe_key TEXT PRIMARY KEY,
    recipe_name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Crafting',
    description TEXT NOT NULL DEFAULT '',
    ingredients JSONB NOT NULL DEFAULT '[]'::jsonb,
    output_item_name TEXT NOT NULL,
    output_quantity INTEGER NOT NULL DEFAULT 1 CHECK(output_quantity>0),
    output_item_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    sort_order INTEGER NOT NULL DEFAULT 100
);

CREATE TABLE IF NOT EXISTS public.discord_crafting_events
(
    crafting_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id UUID NOT NULL REFERENCES public.discord_campaigns(campaign_id) ON DELETE CASCADE,
    character_id UUID NOT NULL REFERENCES public.discord_characters(character_id) ON DELETE CASCADE,
    recipe_key TEXT NOT NULL,
    recipe_name TEXT NOT NULL,
    ingredients JSONB NOT NULL,
    output_item_name TEXT NOT NULL,
    output_quantity INTEGER NOT NULL,
    crafted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_discord_crafting_events_character
ON public.discord_crafting_events(character_id,crafted_at DESC);

ALTER TABLE public.discord_crafting_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_crafting_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.discord_crafting_recipes FROM PUBLIC,anon,authenticated;
REVOKE ALL ON public.discord_crafting_events FROM PUBLIC,anon,authenticated;
GRANT ALL ON public.discord_crafting_recipes TO service_role;
GRANT ALL ON public.discord_crafting_events TO service_role;

INSERT INTO public.discord_crafting_recipes(recipe_key,recipe_name,category,description,ingredients,output_item_name,output_quantity,output_item_data,sort_order)
VALUES
('tanned_leather','Tanned Leather','Leatherworking','Clean and cure a harvested pelt or hide into a durable crafting material.',
 '[{"family":"pelt_hide","label":"Pelt / Hide / Skin","quantity":1}]'::jsonb,
 'Tanned Leather',1,'{"item_type":"Crafting Material","crafting_family":"leather","weight":1,"description":"Prepared leather suitable for armor, clothing, and field repairs."}'::jsonb,10),
('dragon_scale_component','Dragon Scale Armor Component','Armorsmithing','Bind and shape true dragon scales into a reinforced armor component.',
 '[{"family":"dragon_scale","label":"Dragon Scale","quantity":2}]'::jsonb,
 'Dragon Scale Armor Component',1,'{"item_type":"Crafting Material","crafting_family":"dragon_scale_component","weight":1,"description":"A fitted grouping of dragon scales prepared for advanced armor crafting."}'::jsonb,20),
('herbal_poultice','Herbal Healing Poultice','Herbalism','Grind medicinal herbs into a field dressing for minor wounds.',
 '[{"family":"healing_herb","label":"Healing / Medicinal Herb","quantity":2}]'::jsonb,
 'Herbal Healing Poultice',1,'{"item_type":"Consumable","weight":0.2,"description":"A prepared medicinal poultice. The Game Master determines its healing effect when used."}'::jsonb,30),
('potion_of_healing','Potion of Healing','Alchemy','Steep medicinal herbs into a restorative potion and seal it in a vial.',
 '[{"family":"healing_herb","label":"Healing / Medicinal Herb","quantity":3},{"family":"vial","label":"Empty Vial","quantity":1}]'::jsonb,
 'Potion of Healing',1,'{"item_type":"Consumable","weight":0.5,"description":"A standard restorative healing potion."}'::jsonb,40),
('monster_rations','Monster Meat Rations','Cooking','Preserve safe monster meat into one day of travel rations.',
 '[{"family":"monster_meat","label":"Monster Meat","quantity":3}]'::jsonb,
 'Monster Meat Rations (1 day)',1,'{"item_type":"Consumable","weight":2,"description":"Preserved monster meat prepared as one day of rations."}'::jsonb,50),
('bone_reinforcement','Reinforced Bone Component','Bonecraft','Shape bones, horns, claws, or fangs into a hardened reinforcement.',
 '[{"family":"bone_horn","label":"Bone / Horn / Claw / Fang","quantity":2}]'::jsonb,
 'Reinforced Bone Component',1,'{"item_type":"Crafting Material","crafting_family":"bone_reinforcement","weight":1,"description":"A hardened monster-bone component prepared for weapons, armor, or tools."}'::jsonb,60),
('monster_venom_vial','Monster Venom Vial','Alchemy','Extract a harvested venom gland or sac into a sealed vial.',
 '[{"family":"venom","label":"Venom Gland / Sac","quantity":1},{"family":"vial","label":"Empty Vial","quantity":1}]'::jsonb,
 'Monster Venom Vial',1,'{"item_type":"Consumable","weight":0.2,"description":"A sealed dose of monster venom. Its exact poison effect depends on the harvested creature."}'::jsonb,70),
('chitin_armor_plate','Chitin Armor Plate','Armorsmithing','Cut chitin, shell, or carapace into a fitted protective plate.',
 '[{"family":"chitin_shell","label":"Chitin / Shell / Carapace","quantity":2}]'::jsonb,
 'Chitin Armor Plate',1,'{"item_type":"Crafting Material","crafting_family":"chitin_plate","weight":1.5,"description":"A fitted natural armor plate ready for advanced crafting."}'::jsonb,80)
ON CONFLICT(recipe_key) DO UPDATE SET
 recipe_name=EXCLUDED.recipe_name,category=EXCLUDED.category,description=EXCLUDED.description,
 ingredients=EXCLUDED.ingredients,output_item_name=EXCLUDED.output_item_name,
 output_quantity=EXCLUDED.output_quantity,output_item_data=EXCLUDED.output_item_data,sort_order=EXCLUDED.sort_order;

CREATE OR REPLACE FUNCTION public.discord_crafting_material_family(p_item_name TEXT,p_item_data JSONB DEFAULT '{}'::jsonb)
RETURNS TEXT
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE v_name TEXT:=LOWER(TRIM(COALESCE(p_item_name,'')));
BEGIN
    IF v_name='' THEN RETURN NULL; END IF;
    IF (v_name LIKE '%dragon%' AND v_name LIKE '%scale%') THEN RETURN 'dragon_scale'; END IF;
    IF v_name ~ '(healing|medicinal).*(herb|plant|root|flower|moss)' OR v_name ~ '(herb|plant|root|flower|moss).*(healing|medicinal)' OR v_name ~ '(^| )(herb|herbs)( |$)' THEN RETURN 'healing_herb'; END IF;
    IF v_name ~ '(venom|poison).*(gland|sac)' OR v_name ~ '(gland|sac).*(venom|poison)' THEN RETURN 'venom'; END IF;
    IF v_name ~ '(chitin|carapace|shell)' THEN RETURN 'chitin_shell'; END IF;
    IF v_name ~ '(bone|horn|antler|claw|talon|fang|tooth|teeth)' THEN RETURN 'bone_horn'; END IF;
    IF v_name ~ '(pelt|hide|skin)' THEN RETURN 'pelt_hide'; END IF;
    IF v_name ~ '(meat|flesh)' AND v_name NOT LIKE '%ration%' AND v_name NOT LIKE '%prepared%' THEN RETURN 'monster_meat'; END IF;
    IF v_name='vial' OR v_name LIKE '%empty vial%' OR v_name LIKE '%glass vial%' THEN RETURN 'vial'; END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.discord_get_crafting_state(p_player_id UUID,p_campaign_id UUID)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
    v_player UUID;
    v_character_id UUID;
    v_character_name TEXT;
    v_recipe RECORD;
    v_req JSONB;
    v_requirements JSONB;
    v_recipes JSONB:='[]'::jsonb;
    v_materials JSONB:='[]'::jsonb;
    v_available INTEGER;
    v_needed INTEGER;
    v_can BOOLEAN;
    v_family TEXT;
    v_label TEXT;
    v_item RECORD;
BEGIN
    v_player:=public.discord_resolve_active_player(p_player_id,p_campaign_id);
    SELECT c.character_id,c.character_name INTO v_character_id,v_character_name
    FROM public.discord_characters c
    WHERE c.campaign_id=p_campaign_id AND c.player_id=v_player LIMIT 1;
    IF v_character_id IS NULL THEN RAISE EXCEPTION 'Active campaign character could not be found.'; END IF;

    FOR v_item IN
        SELECT i.item_name,SUM(i.quantity)::INTEGER AS quantity,
               public.discord_crafting_material_family(i.item_name,i.item_data) AS family
        FROM public.discord_inventory_items i
        WHERE i.character_id=v_character_id
          AND public.discord_crafting_material_family(i.item_name,i.item_data) IS NOT NULL
        GROUP BY i.item_name,public.discord_crafting_material_family(i.item_name,i.item_data)
        ORDER BY i.item_name
    LOOP
        v_materials:=v_materials||jsonb_build_array(jsonb_build_object(
            'itemName',v_item.item_name,'quantity',v_item.quantity,'family',v_item.family,
            'familyLabel',CASE v_item.family
                WHEN 'dragon_scale' THEN 'Dragon Scale' WHEN 'healing_herb' THEN 'Medicinal Herb'
                WHEN 'venom' THEN 'Venom' WHEN 'chitin_shell' THEN 'Chitin / Shell'
                WHEN 'bone_horn' THEN 'Bonecraft' WHEN 'pelt_hide' THEN 'Pelt / Hide'
                WHEN 'monster_meat' THEN 'Monster Meat' WHEN 'vial' THEN 'Vial' ELSE 'Material' END));
    END LOOP;

    FOR v_recipe IN SELECT * FROM public.discord_crafting_recipes ORDER BY sort_order,recipe_name LOOP
        v_requirements:='[]'::jsonb; v_can:=TRUE;
        FOR v_req IN SELECT value FROM jsonb_array_elements(v_recipe.ingredients) LOOP
            v_family:=COALESCE(v_req->>'family','');
            v_label:=COALESCE(v_req->>'label',v_family);
            v_needed:=GREATEST(1,COALESCE((v_req->>'quantity')::INTEGER,1));
            SELECT COALESCE(SUM(i.quantity),0)::INTEGER INTO v_available
            FROM public.discord_inventory_items i
            WHERE i.character_id=v_character_id AND NOT COALESCE(i.equipped,FALSE)
              AND public.discord_crafting_material_family(i.item_name,i.item_data)=v_family;
            IF v_available<v_needed THEN v_can:=FALSE; END IF;
            v_requirements:=v_requirements||jsonb_build_array(jsonb_build_object(
                'family',v_family,'label',v_label,'needed',v_needed,'available',v_available));
        END LOOP;
        v_recipes:=v_recipes||jsonb_build_array(jsonb_build_object(
            'recipeKey',v_recipe.recipe_key,'recipeName',v_recipe.recipe_name,'category',v_recipe.category,
            'description',v_recipe.description,'requirements',v_requirements,'canCraft',v_can,
            'outputItemName',v_recipe.output_item_name,'outputQuantity',v_recipe.output_quantity));
    END LOOP;

    RETURN jsonb_build_object('characterId',v_character_id,'characterName',v_character_name,'materials',v_materials,'recipes',v_recipes);
END;
$$;

CREATE OR REPLACE FUNCTION public.discord_craft_recipe(p_player_id UUID,p_campaign_id UUID,p_recipe_key TEXT)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
    v_player UUID;
    v_character_id UUID;
    v_character_name TEXT;
    v_recipe public.discord_crafting_recipes%ROWTYPE;
    v_req JSONB;
    v_family TEXT;
    v_needed INTEGER;
    v_available INTEGER;
    v_remaining INTEGER;
    v_take INTEGER;
    v_item RECORD;
    v_output_id UUID;
    v_consumed JSONB:='[]'::jsonb;
BEGIN
    v_player:=public.discord_resolve_active_player(p_player_id,p_campaign_id);
    SELECT c.character_id,c.character_name INTO v_character_id,v_character_name
    FROM public.discord_characters c
    WHERE c.campaign_id=p_campaign_id AND c.player_id=v_player LIMIT 1 FOR UPDATE;
    IF v_character_id IS NULL THEN RAISE EXCEPTION 'Active campaign character could not be found.'; END IF;

    SELECT * INTO v_recipe FROM public.discord_crafting_recipes r
    WHERE r.recipe_key=LOWER(TRIM(COALESCE(p_recipe_key,'')));
    IF v_recipe.recipe_key IS NULL THEN RAISE EXCEPTION 'Unknown crafting recipe.'; END IF;

    FOR v_req IN SELECT value FROM jsonb_array_elements(v_recipe.ingredients) LOOP
        v_family:=COALESCE(v_req->>'family','');
        v_needed:=GREATEST(1,COALESCE((v_req->>'quantity')::INTEGER,1));
        SELECT COALESCE(SUM(i.quantity),0)::INTEGER INTO v_available
        FROM public.discord_inventory_items i
        WHERE i.character_id=v_character_id AND NOT COALESCE(i.equipped,FALSE)
          AND public.discord_crafting_material_family(i.item_name,i.item_data)=v_family;
        IF v_available<v_needed THEN
            RAISE EXCEPTION 'Not enough % to craft %.',COALESCE(v_req->>'label',v_family),v_recipe.recipe_name;
        END IF;
    END LOOP;

    FOR v_req IN SELECT value FROM jsonb_array_elements(v_recipe.ingredients) LOOP
        v_family:=COALESCE(v_req->>'family','');
        v_remaining:=GREATEST(1,COALESCE((v_req->>'quantity')::INTEGER,1));
        FOR v_item IN
            SELECT i.inventory_item_id,i.item_name,i.quantity
            FROM public.discord_inventory_items i
            WHERE i.character_id=v_character_id AND NOT COALESCE(i.equipped,FALSE)
              AND public.discord_crafting_material_family(i.item_name,i.item_data)=v_family
            ORDER BY i.inventory_item_id FOR UPDATE
        LOOP
            EXIT WHEN v_remaining<=0;
            v_take:=LEAST(v_remaining,v_item.quantity);
            v_consumed:=v_consumed||jsonb_build_array(jsonb_build_object(
                'inventoryItemId',v_item.inventory_item_id,'itemName',v_item.item_name,'quantity',v_take,'family',v_family));
            IF v_take>=v_item.quantity THEN
                DELETE FROM public.discord_inventory_items WHERE inventory_item_id=v_item.inventory_item_id;
            ELSE
                UPDATE public.discord_inventory_items SET quantity=quantity-v_take WHERE inventory_item_id=v_item.inventory_item_id;
            END IF;
            v_remaining:=v_remaining-v_take;
        END LOOP;
    END LOOP;

    SELECT i.inventory_item_id INTO v_output_id
    FROM public.discord_inventory_items i
    WHERE i.character_id=v_character_id AND LOWER(i.item_name)=LOWER(v_recipe.output_item_name)
      AND NOT COALESCE(i.equipped,FALSE)
    ORDER BY i.inventory_item_id LIMIT 1 FOR UPDATE;

    IF v_output_id IS NULL THEN
        INSERT INTO public.discord_inventory_items(character_id,item_name,quantity,equipped,attuned,source_name,notes,item_data)
        VALUES(v_character_id,v_recipe.output_item_name,v_recipe.output_quantity,FALSE,FALSE,'Crafting',
               'Crafted with Build 6.22',v_recipe.output_item_data)
        RETURNING inventory_item_id INTO v_output_id;
    ELSE
        UPDATE public.discord_inventory_items
        SET quantity=quantity+v_recipe.output_quantity,
            item_data=CASE WHEN item_data='{}'::jsonb THEN v_recipe.output_item_data ELSE item_data END
        WHERE inventory_item_id=v_output_id;
    END IF;

    INSERT INTO public.discord_crafting_events(campaign_id,character_id,recipe_key,recipe_name,ingredients,output_item_name,output_quantity)
    VALUES(p_campaign_id,v_character_id,v_recipe.recipe_key,v_recipe.recipe_name,v_consumed,v_recipe.output_item_name,v_recipe.output_quantity);

    RETURN jsonb_build_object('success',TRUE,'characterId',v_character_id,'characterName',v_character_name,
        'recipeKey',v_recipe.recipe_key,'recipeName',v_recipe.recipe_name,'outputItemName',v_recipe.output_item_name,
        'outputQuantity',v_recipe.output_quantity,'inventoryItemId',v_output_id,
        'message','Crafted '||v_recipe.output_quantity::TEXT||' × '||v_recipe.output_item_name||'.');
END;
$$;

REVOKE ALL ON FUNCTION public.discord_get_crafting_state(UUID,UUID) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_craft_recipe(UUID,UUID,TEXT) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.discord_get_crafting_state(UUID,UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_craft_recipe(UUID,UUID,TEXT) TO service_role;

COMMIT;
