-- ============================================================
-- RabuShinAIGM Build 6.26
-- Migration 62 - Monster Loot, Harvesting Tables & Crafting Expansion
--
-- Requires:
--   Build 6.22 / Migration 56 crafting
--   Build 6.9 / Migration 30 waterskins
--   Solo active-player resolver
--
-- Real-time spoilage intentionally follows RabuShin's accelerated world:
-- one real hour is approximately one in-game day.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.discord_monster_harvest_sources
(
    harvest_source_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id UUID NOT NULL REFERENCES public.discord_campaigns(campaign_id) ON DELETE CASCADE,
    combat_monster_id UUID NOT NULL,
    monster_name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    max_hp INTEGER NOT NULL DEFAULT 1,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(campaign_id,combat_monster_id)
);

CREATE TABLE IF NOT EXISTS public.discord_monster_harvest_entries
(
    harvest_entry_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    harvest_source_id UUID NOT NULL REFERENCES public.discord_monster_harvest_sources(harvest_source_id) ON DELETE CASCADE,
    item_name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    maximum_quantity INTEGER NOT NULL CHECK(maximum_quantity>0),
    remaining_quantity INTEGER NOT NULL CHECK(remaining_quantity>=0),
    base_dc INTEGER NOT NULL CHECK(base_dc BETWEEN 5 AND 30),
    rarity TEXT NOT NULL DEFAULT 'common'
        CHECK(rarity IN ('common','uncommon','rare','very_rare','legendary')),
    skill_name TEXT NOT NULL DEFAULT 'Survival',
    ability_name TEXT NOT NULL DEFAULT 'wisdom'
        CHECK(ability_name IN ('strength','dexterity','constitution','intelligence','wisdom','charisma')),
    tool_label TEXT NOT NULL DEFAULT '',
    tool_keywords JSONB NOT NULL DEFAULT '[]'::jsonb,
    tool_required BOOLEAN NOT NULL DEFAULT FALSE,
    required_container_family TEXT NOT NULL DEFAULT '',
    spoils_at TIMESTAMPTZ NULL,
    item_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(harvest_source_id,item_name)
);

CREATE TABLE IF NOT EXISTS public.discord_monster_harvest_attempts
(
    harvest_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id UUID NOT NULL REFERENCES public.discord_campaigns(campaign_id) ON DELETE CASCADE,
    character_id UUID NOT NULL REFERENCES public.discord_characters(character_id) ON DELETE CASCADE,
    harvest_source_id UUID NOT NULL REFERENCES public.discord_monster_harvest_sources(harvest_source_id) ON DELETE CASCADE,
    harvest_entry_id UUID NOT NULL REFERENCES public.discord_monster_harvest_entries(harvest_entry_id) ON DELETE CASCADE,
    d20_roll INTEGER NOT NULL CHECK(d20_roll BETWEEN 1 AND 20),
    ability_modifier INTEGER NOT NULL,
    proficiency_applied BOOLEAN NOT NULL DEFAULT FALSE,
    tool_available BOOLEAN NOT NULL DEFAULT FALSE,
    effective_dc INTEGER NOT NULL,
    total INTEGER NOT NULL,
    success BOOLEAN NOT NULL,
    quantity_gained INTEGER NOT NULL DEFAULT 0,
    quantity_lost INTEGER NOT NULL DEFAULT 0,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_discord_harvest_sources_campaign
ON public.discord_monster_harvest_sources(campaign_id,registered_at DESC);

CREATE INDEX IF NOT EXISTS ix_discord_harvest_entries_source
ON public.discord_monster_harvest_entries(harvest_source_id,remaining_quantity);

CREATE INDEX IF NOT EXISTS ix_discord_harvest_attempts_character
ON public.discord_monster_harvest_attempts(character_id,attempted_at DESC);

ALTER TABLE public.discord_monster_harvest_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_monster_harvest_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_monster_harvest_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.discord_monster_harvest_sources FROM PUBLIC,anon,authenticated;
REVOKE ALL ON public.discord_monster_harvest_entries FROM PUBLIC,anon,authenticated;
REVOKE ALL ON public.discord_monster_harvest_attempts FROM PUBLIC,anon,authenticated;
GRANT ALL ON public.discord_monster_harvest_sources TO service_role;
GRANT ALL ON public.discord_monster_harvest_entries TO service_role;
GRANT ALL ON public.discord_monster_harvest_attempts TO service_role;

-- Explicit recipe metadata takes priority. This makes intermediate crafted
-- materials (Tanned Leather, Cordage, etc.) reliable ingredients.
CREATE OR REPLACE FUNCTION public.discord_crafting_material_family(
    p_item_name TEXT,
    p_item_data JSONB DEFAULT '{}'::jsonb
)
RETURNS TEXT
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE
    v_name TEXT:=LOWER(TRIM(COALESCE(p_item_name,'')));
    v_explicit TEXT:=LOWER(TRIM(COALESCE(p_item_data->>'crafting_family','')));
BEGIN
    IF v_explicit<>'' THEN RETURN v_explicit; END IF;
    IF v_name='' THEN RETURN NULL; END IF;
    IF v_name='tanned leather' OR v_name='prepared leather' THEN RETURN 'leather'; END IF;
    IF v_name='cordage' OR v_name LIKE '%leather cord%' OR v_name LIKE '%plant cord%' OR v_name LIKE '%twine%' THEN RETURN 'cordage'; END IF;
    IF v_name LIKE '%dragon%' AND v_name LIKE '%blood%' THEN RETURN 'dragon_blood'; END IF;
    IF (v_name LIKE '%dragon%' AND v_name LIKE '%scale%') THEN RETURN 'dragon_scale'; END IF;
    IF v_name ~ '(healing|medicinal).*(herb|plant|root|flower|moss)' OR
       v_name ~ '(herb|plant|root|flower|moss).*(healing|medicinal)' OR
       v_name ~ '(^| )(herb|herbs)( |$)' THEN RETURN 'healing_herb'; END IF;
    IF v_name ~ '(venom|poison).*(gland|sac)' OR v_name ~ '(gland|sac).*(venom|poison)' THEN RETURN 'venom'; END IF;
    IF v_name ~ '(chitin|carapace|shell)' THEN RETURN 'chitin_shell'; END IF;
    IF v_name ~ '(bone|horn|antler|claw|talon|fang|tooth|teeth|tusk)' THEN RETURN 'bone_horn'; END IF;
    IF v_name ~ '(pelt|hide|skin)' THEN RETURN 'pelt_hide'; END IF;
    IF v_name ~ '(meat|flesh)' AND v_name NOT LIKE '%ration%' AND v_name NOT LIKE '%prepared%' THEN RETURN 'monster_meat'; END IF;
    IF v_name ~ '(plant fiber|vine fiber|fibrous vine|sinew)' THEN RETURN 'plant_fiber'; END IF;
    IF v_name ~ '(ooze|slime|membrane)' THEN RETURN 'ooze_residue'; END IF;
    IF v_name ~ '(elemental essence|cinder core|frost crystal|elemental dust|elemental stone)' THEN RETURN 'elemental_essence'; END IF;
    IF v_name LIKE '%ectoplasm%' THEN RETURN 'ectoplasm'; END IF;
    IF v_name ~ '(construct component|arcane scrap)' THEN RETURN 'construct_salvage'; END IF;
    IF v_name='vial' OR v_name LIKE '%empty vial%' OR v_name LIKE '%glass vial%' THEN RETURN 'vial'; END IF;
    RETURN NULL;
END;
$$;

-- New harvested-material recipes. Waterskin is intentionally a normal
-- craftable item and is created through the existing waterskin-aware RPC.
INSERT INTO public.discord_crafting_recipes(
    recipe_key,recipe_name,category,description,ingredients,
    output_item_name,output_quantity,output_item_data,sort_order
)
VALUES
(
    'field_cordage','Field Cordage','Fieldcraft',
    'Twist harvested plant fiber or sinew into strong cordage for containers, repairs, and other fieldcraft.',
    '[{"family":"plant_fiber","label":"Plant Fiber / Sinew","quantity":2}]'::jsonb,
    'Cordage',1,
    '{"item_type":"Crafting Material","crafting_family":"cordage","weight":0.5,"description":"Strong hand-made cordage suitable for fieldcraft and leatherworking."}'::jsonb,
    85
),
(
    'waterskin','Waterskin','Leatherworking',
    'Stitch prepared leather around a sealed bladder shape and bind it with cordage. The finished Waterskin starts empty and uses the normal 30-drink waterskin rules.',
    '[{"family":"leather","label":"Tanned Leather","quantity":2},{"family":"cordage","label":"Cordage","quantity":1}]'::jsonb,
    'Waterskin',1,
    '{"item_type":"Adventuring Gear","weight":1,"description":"A durable leather water container. It holds 30 drinks, equal to 3 days of water."}'::jsonb,
    90
),
(
    'dragon_blood_tempering','Draconic Tempering Reagent','Alchemy',
    'Stabilize freshly harvested dragon blood into a reagent for advanced draconic crafting.',
    '[{"family":"dragon_blood","label":"Dragon Blood Vial","quantity":1}]'::jsonb,
    'Draconic Tempering Reagent',1,
    '{"item_type":"Crafting Material","crafting_family":"draconic_reagent","weight":0.2,"description":"A stabilized draconic reagent used in advanced weapons, armor, and alchemy."}'::jsonb,
    95
),
(
    'ooze_adhesive','Ooze Adhesive','Alchemy',
    'Refine harvested ooze residue into a strong alchemical bonding agent.',
    '[{"family":"ooze_residue","label":"Ooze Residue","quantity":2}]'::jsonb,
    'Ooze Adhesive',1,
    '{"item_type":"Crafting Material","crafting_family":"alchemical_adhesive","weight":0.5,"description":"A sticky refined compound useful for repairs and advanced crafting."}'::jsonb,
    96
),
(
    'elemental_reagent','Elemental Infusion','Alchemy',
    'Stabilize condensed elemental essence into an advanced magical crafting reagent.',
    '[{"family":"elemental_essence","label":"Elemental Essence","quantity":2}]'::jsonb,
    'Elemental Infusion',1,
    '{"item_type":"Crafting Material","crafting_family":"elemental_infusion","weight":0.2,"description":"A stabilized infusion carrying concentrated elemental energy."}'::jsonb,
    97
)
ON CONFLICT(recipe_key) DO UPDATE SET
    recipe_name=EXCLUDED.recipe_name,
    category=EXCLUDED.category,
    description=EXCLUDED.description,
    ingredients=EXCLUDED.ingredients,
    output_item_name=EXCLUDED.output_item_name,
    output_quantity=EXCLUDED.output_quantity,
    output_item_data=EXCLUDED.output_item_data,
    sort_order=EXCLUDED.sort_order;

-- Build 6.26 keeps all Build 6.22 ingredient consumption rules but routes a
-- crafted Waterskin through discord_gm_add_inventory_item so its individual
-- discord_waterskin_state row is created immediately.
CREATE OR REPLACE FUNCTION public.discord_craft_recipe(
    p_player_id UUID,
    p_campaign_id UUID,
    p_recipe_key TEXT
)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
    v_player UUID;
    v_character_id UUID;
    v_character_name TEXT;
    v_recipe public.discord_crafting_recipes%ROWTYPE;
    v_req JSONB;
    v_family TEXT;
    v_needed INTEGER;
    v_available INTEGER;
    v_remaining INTEGER;
    v_take INTEGER;
    v_item RECORD;
    v_output_id UUID;
    v_consumed JSONB:='[]'::jsonb;
BEGIN
    v_player:=public.discord_resolve_active_player(p_player_id,p_campaign_id);
    SELECT c.character_id,c.character_name INTO v_character_id,v_character_name
    FROM public.discord_characters c
    WHERE c.campaign_id=p_campaign_id AND c.player_id=v_player LIMIT 1 FOR UPDATE;
    IF v_character_id IS NULL THEN RAISE EXCEPTION 'Active campaign character could not be found.'; END IF;

    SELECT * INTO v_recipe FROM public.discord_crafting_recipes r
    WHERE r.recipe_key=LOWER(TRIM(COALESCE(p_recipe_key,'')));
    IF v_recipe.recipe_key IS NULL THEN RAISE EXCEPTION 'Unknown crafting recipe.'; END IF;

    FOR v_req IN SELECT value FROM jsonb_array_elements(v_recipe.ingredients) LOOP
        v_family:=COALESCE(v_req->>'family','');
        v_needed:=GREATEST(1,COALESCE((v_req->>'quantity')::INTEGER,1));
        SELECT COALESCE(SUM(i.quantity),0)::INTEGER INTO v_available
        FROM public.discord_inventory_items i
        WHERE i.character_id=v_character_id AND NOT COALESCE(i.equipped,FALSE)
          AND public.discord_crafting_material_family(i.item_name,i.item_data)=v_family;
        IF v_available<v_needed THEN
            RAISE EXCEPTION 'Not enough % to craft %.',COALESCE(v_req->>'label',v_family),v_recipe.recipe_name;
        END IF;
    END LOOP;

    FOR v_req IN SELECT value FROM jsonb_array_elements(v_recipe.ingredients) LOOP
        v_family:=COALESCE(v_req->>'family','');
        v_remaining:=GREATEST(1,COALESCE((v_req->>'quantity')::INTEGER,1));
        FOR v_item IN
            SELECT i.inventory_item_id,i.item_name,i.quantity
            FROM public.discord_inventory_items i
            WHERE i.character_id=v_character_id AND NOT COALESCE(i.equipped,FALSE)
              AND public.discord_crafting_material_family(i.item_name,i.item_data)=v_family
            ORDER BY i.inventory_item_id FOR UPDATE
        LOOP
            EXIT WHEN v_remaining<=0;
            v_take:=LEAST(v_remaining,v_item.quantity);
            v_consumed:=v_consumed||jsonb_build_array(jsonb_build_object(
                'inventoryItemId',v_item.inventory_item_id,'itemName',v_item.item_name,
                'quantity',v_take,'family',v_family));
            IF v_take>=v_item.quantity THEN
                DELETE FROM public.discord_inventory_items WHERE inventory_item_id=v_item.inventory_item_id;
            ELSE
                UPDATE public.discord_inventory_items
                SET quantity=quantity-v_take,updated_at=NOW()
                WHERE inventory_item_id=v_item.inventory_item_id;
            END IF;
            v_remaining:=v_remaining-v_take;
        END LOOP;
    END LOOP;

    IF LOWER(TRIM(v_recipe.output_item_name))='waterskin' THEN
        PERFORM public.discord_gm_add_inventory_item(
            v_character_id,p_campaign_id,'Waterskin',v_recipe.output_quantity,
            COALESCE(v_recipe.output_item_data->>'description','A durable leather water container. It holds 30 drinks, equal to 3 days of water.'),
            'Crafting','Crafted with Build 6.26'
        );
        SELECT i.inventory_item_id INTO v_output_id
        FROM public.discord_inventory_items i
        INNER JOIN public.discord_waterskin_state ws ON ws.inventory_item_id=i.inventory_item_id
        WHERE i.character_id=v_character_id
          AND LOWER(TRIM(i.item_name))='waterskin'
          AND ws.campaign_id=p_campaign_id
        ORDER BY i.created_at DESC,i.inventory_item_id DESC
        LIMIT 1;
    ELSE
        SELECT i.inventory_item_id INTO v_output_id
        FROM public.discord_inventory_items i
        WHERE i.character_id=v_character_id AND LOWER(i.item_name)=LOWER(v_recipe.output_item_name)
          AND NOT COALESCE(i.equipped,FALSE)
        ORDER BY i.inventory_item_id LIMIT 1 FOR UPDATE;

        IF v_output_id IS NULL THEN
            INSERT INTO public.discord_inventory_items(
                character_id,item_name,quantity,equipped,attuned,source_name,notes,item_data)
            VALUES(
                v_character_id,v_recipe.output_item_name,v_recipe.output_quantity,FALSE,FALSE,
                'Crafting','Crafted with Build 6.26',v_recipe.output_item_data)
            RETURNING inventory_item_id INTO v_output_id;
        ELSE
            UPDATE public.discord_inventory_items
            SET quantity=quantity+v_recipe.output_quantity,
                item_data=CASE WHEN item_data='{}'::jsonb THEN v_recipe.output_item_data ELSE item_data END,
                updated_at=NOW()
            WHERE inventory_item_id=v_output_id;
        END IF;
    END IF;

    INSERT INTO public.discord_crafting_events(
        campaign_id,character_id,recipe_key,recipe_name,ingredients,output_item_name,output_quantity)
    VALUES(
        p_campaign_id,v_character_id,v_recipe.recipe_key,v_recipe.recipe_name,v_consumed,
        v_recipe.output_item_name,v_recipe.output_quantity);

    RETURN jsonb_build_object(
        'success',TRUE,
        'characterId',v_character_id,
        'characterName',v_character_name,
        'recipeKey',v_recipe.recipe_key,
        'recipeName',v_recipe.recipe_name,
        'outputItemName',v_recipe.output_item_name,
        'outputQuantity',v_recipe.output_quantity,
        'inventoryItemId',v_output_id,
        'message','Crafted '||v_recipe.output_quantity::TEXT||' × '||v_recipe.output_item_name||'.');
END;
$$;

-- Trusted server discovery. This keeps monster identity and defeat state
-- authoritative and prevents clients from inventing harvest sources.
DROP FUNCTION IF EXISTS public.discord_get_unseeded_defeated_monsters(UUID);
CREATE OR REPLACE FUNCTION public.discord_get_unseeded_defeated_monsters(
    p_campaign_id UUID
)
RETURNS TABLE(
    combat_monster_id UUID,
    monster_name TEXT,
    display_name TEXT,
    max_hp INTEGER
)
LANGUAGE sql
SECURITY DEFINER
SET search_path=public AS $$
    SELECT m.combat_monster_id,m.monster_name,m.display_name,GREATEST(1,COALESCE(m.max_hp,1))
    FROM public.discord_campaign_combat_monsters m
    WHERE m.campaign_id=p_campaign_id
      AND (COALESCE(m.defeated,FALSE)=TRUE OR COALESCE(m.current_hp,0)<=0)
      AND NOT EXISTS (
          SELECT 1
          FROM public.discord_monster_harvest_sources s
          WHERE s.campaign_id=p_campaign_id
            AND s.combat_monster_id=m.combat_monster_id
      )
    ORDER BY m.created_at,m.combat_monster_id;
$$;

DROP FUNCTION IF EXISTS public.discord_seed_monster_harvest_source(UUID,UUID,JSONB);
CREATE OR REPLACE FUNCTION public.discord_seed_monster_harvest_source(
    p_campaign_id UUID,
    p_combat_monster_id UUID,
    p_entries JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public AS $$
DECLARE
    v_monster RECORD;
    v_source_id UUID;
    v_entry JSONB;
    v_item_name TEXT;
    v_qty INTEGER;
    v_spoil_minutes INTEGER;
BEGIN
    SELECT m.combat_monster_id,m.monster_name,m.display_name,m.max_hp,m.defeated,m.current_hp
    INTO v_monster
    FROM public.discord_campaign_combat_monsters m
    WHERE m.campaign_id=p_campaign_id
      AND m.combat_monster_id=p_combat_monster_id
    LIMIT 1;

    IF v_monster.combat_monster_id IS NULL THEN
        RAISE EXCEPTION 'Combat monster could not be found.';
    END IF;
    IF NOT COALESCE(v_monster.defeated,FALSE) AND COALESCE(v_monster.current_hp,1)>0 THEN
        RAISE EXCEPTION 'Only a defeated monster can become a harvest source.';
    END IF;
    IF p_entries IS NULL OR jsonb_typeof(p_entries)<>'array' THEN
        RAISE EXCEPTION 'Harvest entries must be a JSON array.';
    END IF;

    INSERT INTO public.discord_monster_harvest_sources(
        campaign_id,combat_monster_id,monster_name,display_name,max_hp)
    VALUES(
        p_campaign_id,p_combat_monster_id,v_monster.monster_name,v_monster.display_name,
        GREATEST(1,COALESCE(v_monster.max_hp,1)))
    ON CONFLICT(campaign_id,combat_monster_id) DO UPDATE
    SET display_name=EXCLUDED.display_name,
        monster_name=EXCLUDED.monster_name,
        max_hp=EXCLUDED.max_hp
    RETURNING harvest_source_id INTO v_source_id;

    FOR v_entry IN SELECT value FROM jsonb_array_elements(p_entries) LOOP
        v_item_name:=TRIM(COALESCE(v_entry->>'itemName',''));
        IF v_item_name='' THEN CONTINUE; END IF;
        v_qty:=GREATEST(1,LEAST(1000,COALESCE((v_entry->>'maximumQuantity')::INTEGER,1)));
        v_spoil_minutes:=NULLIF(COALESCE((v_entry->>'spoilageMinutes')::INTEGER,0),0);

        INSERT INTO public.discord_monster_harvest_entries(
            harvest_source_id,item_name,description,maximum_quantity,remaining_quantity,
            base_dc,rarity,skill_name,ability_name,tool_label,tool_keywords,tool_required,
            required_container_family,spoils_at,item_data)
        VALUES(
            v_source_id,
            v_item_name,
            COALESCE(v_entry->>'description',''),
            v_qty,
            v_qty,
            GREATEST(5,LEAST(30,COALESCE((v_entry->>'baseDc')::INTEGER,10))),
            CASE WHEN COALESCE(v_entry->>'rarity','common') IN ('common','uncommon','rare','very_rare','legendary')
                 THEN v_entry->>'rarity' ELSE 'common' END,
            COALESCE(NULLIF(v_entry->>'skillName',''),'Survival'),
            CASE WHEN COALESCE(v_entry->>'abilityName','wisdom') IN
                     ('strength','dexterity','constitution','intelligence','wisdom','charisma')
                 THEN v_entry->>'abilityName' ELSE 'wisdom' END,
            COALESCE(v_entry->>'toolLabel',''),
            CASE WHEN jsonb_typeof(v_entry->'toolKeywords')='array' THEN v_entry->'toolKeywords' ELSE '[]'::jsonb END,
            COALESCE((v_entry->>'toolRequired')::BOOLEAN,FALSE),
            COALESCE(v_entry->>'requiredContainerFamily',''),
            CASE WHEN v_spoil_minutes IS NULL THEN NULL ELSE NOW()+(v_spoil_minutes||' minutes')::INTERVAL END,
            CASE WHEN jsonb_typeof(v_entry->'itemData')='object' THEN v_entry->'itemData' ELSE '{}'::jsonb END
        )
        ON CONFLICT(harvest_source_id,item_name) DO NOTHING;
    END LOOP;

    RETURN jsonb_build_object(
        'success',TRUE,
        'harvestSourceId',v_source_id,
        'entryCount',(SELECT COUNT(*) FROM public.discord_monster_harvest_entries e WHERE e.harvest_source_id=v_source_id));
END;
$$;

CREATE OR REPLACE FUNCTION public.discord_character_has_skill_proficiency(
    p_character_data JSONB,
    p_skill TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE
    v_skill TEXT:=LOWER(TRIM(COALESCE(p_skill,'')));
    v_value JSONB;
    v_entry TEXT;
BEGIN
    IF v_skill='' OR p_character_data IS NULL OR jsonb_typeof(p_character_data)<>'object' THEN RETURN FALSE; END IF;

    FOR v_value IN
        SELECT value
        FROM jsonb_array_elements(
            CASE
                WHEN jsonb_typeof(p_character_data->'skillProficiencies')='array' THEN p_character_data->'skillProficiencies'
                WHEN jsonb_typeof(p_character_data->'skill_proficiencies')='array' THEN p_character_data->'skill_proficiencies'
                WHEN jsonb_typeof(p_character_data->'skills')='array' THEN p_character_data->'skills'
                WHEN jsonb_typeof(p_character_data#>'{proficiencies,skills}')='array' THEN p_character_data#>'{proficiencies,skills}'
                ELSE '[]'::jsonb
            END
        )
    LOOP
        v_entry:=LOWER(TRIM(BOTH '"' FROM v_value::TEXT));
        IF v_entry=v_skill THEN RETURN TRUE; END IF;
    END LOOP;

    IF jsonb_typeof(p_character_data->'skills')='object' THEN
        IF EXISTS (
            SELECT 1
            FROM jsonb_each(p_character_data->'skills') s
            WHERE LOWER(s.key)=v_skill
              AND (
                  s.value='true'::jsonb OR
                  LOWER(TRIM(BOTH '"' FROM s.value::TEXT)) IN ('proficient','true','yes')
              )
        ) THEN RETURN TRUE; END IF;
    END IF;

    RETURN FALSE;
END;
$$;

DROP FUNCTION IF EXISTS public.discord_get_monster_harvest_state(UUID,UUID);
CREATE OR REPLACE FUNCTION public.discord_get_monster_harvest_state(
    p_player_id UUID,
    p_campaign_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public AS $$
DECLARE
    v_player UUID;
    v_character RECORD;
    v_sources JSONB:='[]'::jsonb;
    v_source RECORD;
    v_entries JSONB;
BEGIN
    v_player:=public.discord_resolve_active_player(p_player_id,p_campaign_id);

    SELECT c.* INTO v_character
    FROM public.discord_characters c
    WHERE c.campaign_id=p_campaign_id AND c.player_id=v_player
    LIMIT 1;
    IF v_character.character_id IS NULL THEN RAISE EXCEPTION 'Active campaign character could not be found.'; END IF;

    FOR v_source IN
        SELECT s.*
        FROM public.discord_monster_harvest_sources s
        WHERE s.campaign_id=p_campaign_id
          AND EXISTS (
              SELECT 1 FROM public.discord_monster_harvest_entries e
              WHERE e.harvest_source_id=s.harvest_source_id
                AND e.remaining_quantity>0
          )
        ORDER BY s.registered_at DESC,s.display_name
    LOOP
        SELECT COALESCE(jsonb_agg(
            jsonb_build_object(
                'harvestEntryId',e.harvest_entry_id,
                'itemName',e.item_name,
                'description',e.description,
                'remainingQuantity',e.remaining_quantity,
                'maximumQuantity',e.maximum_quantity,
                'dc',e.base_dc,
                'rarity',e.rarity,
                'skillName',e.skill_name,
                'abilityName',e.ability_name,
                'skillProficient',public.discord_character_has_skill_proficiency(v_character.character_data,e.skill_name),
                'toolLabel',e.tool_label,
                'toolAvailable',EXISTS(
                    SELECT 1
                    FROM public.discord_inventory_items i
                    CROSS JOIN LATERAL jsonb_array_elements_text(e.tool_keywords) kw
                    WHERE i.character_id=v_character.character_id
                      AND LOWER(i.item_name) LIKE '%'||LOWER(kw.value)||'%'
                ),
                'toolRequired',e.tool_required,
                'requiredContainerFamily',e.required_container_family,
                'containerAvailable',CASE WHEN e.required_container_family='' THEN TRUE ELSE EXISTS(
                    SELECT 1
                    FROM public.discord_inventory_items i
                    WHERE i.character_id=v_character.character_id
                      AND NOT COALESCE(i.equipped,FALSE)
                      AND public.discord_crafting_material_family(i.item_name,i.item_data)=e.required_container_family
                      AND i.quantity>0
                ) END,
                'spoilsAt',e.spoils_at,
                'spoiled',e.spoils_at IS NOT NULL AND e.spoils_at<=NOW(),
                'freshnessLabel',CASE
                    WHEN e.spoils_at IS NULL THEN 'Durable'
                    WHEN e.spoils_at<=NOW() THEN 'Spoiled'
                    WHEN EXTRACT(EPOCH FROM (e.spoils_at-NOW()))<3600
                        THEN GREATEST(1,FLOOR(EXTRACT(EPOCH FROM (e.spoils_at-NOW()))/60))::INTEGER::TEXT||' min fresh'
                    ELSE ROUND((EXTRACT(EPOCH FROM (e.spoils_at-NOW()))/3600.0)::NUMERIC,1)::TEXT||' hr fresh'
                END
            )
            ORDER BY e.base_dc,e.item_name
        ),'[]'::jsonb)
        INTO v_entries
        FROM public.discord_monster_harvest_entries e
        WHERE e.harvest_source_id=v_source.harvest_source_id
          AND e.remaining_quantity>0;

        v_sources:=v_sources||jsonb_build_array(jsonb_build_object(
            'harvestSourceId',v_source.harvest_source_id,
            'monsterName',v_source.monster_name,
            'displayName',v_source.display_name,
            'maxHp',v_source.max_hp,
            'registeredAt',v_source.registered_at,
            'entries',v_entries
        ));
    END LOOP;

    RETURN jsonb_build_object(
        'characterId',v_character.character_id,
        'characterName',v_character.character_name,
        'sources',v_sources,
        'rules',jsonb_build_object(
            'serverRolls',TRUE,
            'toolBonus','A suitable carried tool or known skill proficiency adds the character proficiency bonus.',
            'missingTool','If a recommended tool is missing, the harvesting DC increases by 2. Required containers must be carried.',
            'yield','Success gains 1 unit, +1 at DC+5, +1 at DC+10, and +1 on a natural 20, capped by remaining material.',
            'failure','A failed attempt damages one recoverable unit; a natural 1 damages two.',
            'spoilage','Fresh biological or unstable materials can become unharvestable with real-time spoilage.'
        )
    );
END;
$$;

DROP FUNCTION IF EXISTS public.discord_attempt_monster_harvest(UUID,UUID,UUID,INTEGER);
CREATE OR REPLACE FUNCTION public.discord_attempt_monster_harvest(
    p_player_id UUID,
    p_campaign_id UUID,
    p_harvest_entry_id UUID,
    p_d20_roll INTEGER
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public AS $$
DECLARE
    v_player UUID;
    v_character RECORD;
    v_entry RECORD;
    v_source RECORD;
    v_ability_score INTEGER;
    v_ability_mod INTEGER;
    v_skill_prof BOOLEAN:=FALSE;
    v_tool_available BOOLEAN:=FALSE;
    v_prof_applied BOOLEAN:=FALSE;
    v_effective_dc INTEGER;
    v_total INTEGER;
    v_success BOOLEAN;
    v_quantity INTEGER:=0;
    v_lost INTEGER:=0;
    v_output_id UUID;
    v_container RECORD;
BEGIN
    IF p_d20_roll NOT BETWEEN 1 AND 20 THEN RAISE EXCEPTION 'Harvest d20 roll must be between 1 and 20.'; END IF;

    v_player:=public.discord_resolve_active_player(p_player_id,p_campaign_id);
    SELECT c.* INTO v_character
    FROM public.discord_characters c
    WHERE c.campaign_id=p_campaign_id AND c.player_id=v_player
    LIMIT 1 FOR UPDATE;
    IF v_character.character_id IS NULL THEN RAISE EXCEPTION 'Active campaign character could not be found.'; END IF;

    SELECT e.* INTO v_entry
    FROM public.discord_monster_harvest_entries e
    INNER JOIN public.discord_monster_harvest_sources s ON s.harvest_source_id=e.harvest_source_id
    WHERE e.harvest_entry_id=p_harvest_entry_id AND s.campaign_id=p_campaign_id
    FOR UPDATE OF e;
    IF v_entry.harvest_entry_id IS NULL THEN RAISE EXCEPTION 'Harvestable material could not be found.'; END IF;

    SELECT * INTO v_source
    FROM public.discord_monster_harvest_sources s
    WHERE s.harvest_source_id=v_entry.harvest_source_id;

    IF v_entry.remaining_quantity<=0 THEN RAISE EXCEPTION 'No recoverable material remains.'; END IF;
    IF v_entry.spoils_at IS NOT NULL AND v_entry.spoils_at<=NOW() THEN
        RAISE EXCEPTION '% has spoiled and can no longer be harvested.',v_entry.item_name;
    END IF;

    SELECT CASE v_entry.ability_name
        WHEN 'strength' THEN v_character.strength
        WHEN 'dexterity' THEN v_character.dexterity
        WHEN 'constitution' THEN v_character.constitution
        WHEN 'intelligence' THEN v_character.intelligence
        WHEN 'charisma' THEN v_character.charisma
        ELSE v_character.wisdom
    END INTO v_ability_score;
    v_ability_mod:=FLOOR((COALESCE(v_ability_score,10)-10)/2.0)::INTEGER;

    v_skill_prof:=public.discord_character_has_skill_proficiency(v_character.character_data,v_entry.skill_name);

    SELECT EXISTS(
        SELECT 1
        FROM public.discord_inventory_items i
        CROSS JOIN LATERAL jsonb_array_elements_text(v_entry.tool_keywords) kw
        WHERE i.character_id=v_character.character_id
          AND LOWER(i.item_name) LIKE '%'||LOWER(kw.value)||'%'
    ) INTO v_tool_available;

    IF v_entry.tool_required AND NOT v_tool_available THEN
        RAISE EXCEPTION 'Harvesting % requires: %.',v_entry.item_name,v_entry.tool_label;
    END IF;

    IF v_entry.required_container_family<>'' THEN
        SELECT i.inventory_item_id,i.quantity INTO v_container
        FROM public.discord_inventory_items i
        WHERE i.character_id=v_character.character_id
          AND NOT COALESCE(i.equipped,FALSE)
          AND public.discord_crafting_material_family(i.item_name,i.item_data)=v_entry.required_container_family
          AND i.quantity>0
        ORDER BY i.created_at,i.inventory_item_id
        LIMIT 1
        FOR UPDATE;
        IF v_container.inventory_item_id IS NULL THEN
            RAISE EXCEPTION 'Harvesting % requires an available % container.',v_entry.item_name,v_entry.required_container_family;
        END IF;
    END IF;

    v_prof_applied:=v_skill_prof OR v_tool_available;
    v_effective_dc:=LEAST(30,v_entry.base_dc + CASE WHEN NOT v_tool_available AND jsonb_array_length(v_entry.tool_keywords)>0 THEN 2 ELSE 0 END);
    v_total:=p_d20_roll+v_ability_mod+CASE WHEN v_prof_applied THEN COALESCE(v_character.proficiency_bonus,2) ELSE 0 END;
    v_success:=v_total>=v_effective_dc;

    IF v_success THEN
        v_quantity:=1
            + CASE WHEN v_total>=v_effective_dc+5 THEN 1 ELSE 0 END
            + CASE WHEN v_total>=v_effective_dc+10 THEN 1 ELSE 0 END
            + CASE WHEN p_d20_roll=20 THEN 1 ELSE 0 END;
        v_quantity:=LEAST(v_quantity,v_entry.remaining_quantity);

        IF v_entry.required_container_family<>'' THEN
            IF v_container.quantity<=1 THEN
                DELETE FROM public.discord_inventory_items WHERE inventory_item_id=v_container.inventory_item_id;
            ELSE
                UPDATE public.discord_inventory_items
                SET quantity=quantity-1,updated_at=NOW()
                WHERE inventory_item_id=v_container.inventory_item_id;
            END IF;
        END IF;

        SELECT i.inventory_item_id INTO v_output_id
        FROM public.discord_inventory_items i
        WHERE i.character_id=v_character.character_id
          AND LOWER(i.item_name)=LOWER(v_entry.item_name)
          AND NOT COALESCE(i.equipped,FALSE)
        ORDER BY i.created_at,i.inventory_item_id
        LIMIT 1
        FOR UPDATE;

        IF v_output_id IS NULL THEN
            INSERT INTO public.discord_inventory_items(
                character_id,item_name,quantity,equipped,attuned,source_name,notes,item_data)
            VALUES(
                v_character.character_id,v_entry.item_name,v_quantity,FALSE,FALSE,
                'Harvesting: '||v_source.display_name,
                'Harvested from '||v_source.display_name||' with Build 6.26.',
                COALESCE(v_entry.item_data,'{}'::jsonb)||
                jsonb_build_object('harvest_source_id',v_source.harvest_source_id,'harvested_at',NOW()))
            RETURNING inventory_item_id INTO v_output_id;
        ELSE
            UPDATE public.discord_inventory_items
            SET quantity=quantity+v_quantity,
                item_data=COALESCE(item_data,'{}'::jsonb)||COALESCE(v_entry.item_data,'{}'::jsonb),
                updated_at=NOW()
            WHERE inventory_item_id=v_output_id;
        END IF;

        UPDATE public.discord_monster_harvest_entries
        SET remaining_quantity=remaining_quantity-v_quantity
        WHERE harvest_entry_id=v_entry.harvest_entry_id;
    ELSE
        v_lost:=LEAST(v_entry.remaining_quantity,CASE WHEN p_d20_roll=1 THEN 2 ELSE 1 END);
        UPDATE public.discord_monster_harvest_entries
        SET remaining_quantity=remaining_quantity-v_lost
        WHERE harvest_entry_id=v_entry.harvest_entry_id;
    END IF;

    INSERT INTO public.discord_monster_harvest_attempts(
        campaign_id,character_id,harvest_source_id,harvest_entry_id,d20_roll,
        ability_modifier,proficiency_applied,tool_available,effective_dc,total,
        success,quantity_gained,quantity_lost)
    VALUES(
        p_campaign_id,v_character.character_id,v_source.harvest_source_id,v_entry.harvest_entry_id,
        p_d20_roll,v_ability_mod,v_prof_applied,v_tool_available,v_effective_dc,v_total,
        v_success,v_quantity,v_lost);

    RETURN jsonb_build_object(
        'success',v_success,
        'roll',p_d20_roll,
        'abilityModifier',v_ability_mod,
        'proficiencyApplied',v_prof_applied,
        'toolAvailable',v_tool_available,
        'dc',v_effective_dc,
        'total',v_total,
        'itemName',v_entry.item_name,
        'quantityGained',v_quantity,
        'quantityLost',v_lost,
        'inventoryItemId',v_output_id,
        'message',CASE
            WHEN v_success THEN 'Harvest succeeded: '||v_quantity::TEXT||' × '||v_entry.item_name||' recovered (check '||v_total::TEXT||' vs DC '||v_effective_dc::TEXT||').'
            ELSE 'Harvest failed (check '||v_total::TEXT||' vs DC '||v_effective_dc::TEXT||'); '||v_lost::TEXT||' recoverable unit(s) were damaged.'
        END
    );
END;
$$;

REVOKE ALL ON FUNCTION public.discord_get_unseeded_defeated_monsters(UUID) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_seed_monster_harvest_source(UUID,UUID,JSONB) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_get_monster_harvest_state(UUID,UUID) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_attempt_monster_harvest(UUID,UUID,UUID,INTEGER) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_character_has_skill_proficiency(JSONB,TEXT) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_craft_recipe(UUID,UUID,TEXT) FROM PUBLIC,anon,authenticated;

GRANT EXECUTE ON FUNCTION public.discord_get_unseeded_defeated_monsters(UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_seed_monster_harvest_source(UUID,UUID,JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_get_monster_harvest_state(UUID,UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_attempt_monster_harvest(UUID,UUID,UUID,INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_character_has_skill_proficiency(JSONB,TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_craft_recipe(UUID,UUID,TEXT) TO service_role;

NOTIFY pgrst,'reload schema';

COMMIT;
