-- ============================================================
-- RabuShinAIGM Build 6.29
-- Migration 63 - Economy, Merchants & Dynamic Shops
--
-- Requires:
--   Migration 24 exact multi-currency helper
--   Migration 49 faction reputation
--   Migration 56/62 crafting and harvesting
--   Migration 57 equipment loadouts
--
-- Server-authoritative economy:
--   The client never supplies merchant price, wealth, stock, scarcity,
--   reputation multipliers, condition multipliers, or service price.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.discord_economy_shops
(
    shop_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id UUID NOT NULL REFERENCES public.discord_campaigns(campaign_id) ON DELETE CASCADE,
    settlement_key TEXT NOT NULL,
    settlement_name TEXT NOT NULL,
    poi_key TEXT NOT NULL,
    shop_name TEXT NOT NULL,
    shop_kind TEXT NOT NULL,
    settlement_multiplier NUMERIC(6,3) NOT NULL DEFAULT 1.000,
    wealth_gp NUMERIC(12,2) NOT NULL DEFAULT 100.00 CHECK(wealth_gp >= 0),
    wealth_cap_gp NUMERIC(12,2) NOT NULL DEFAULT 100.00 CHECK(wealth_cap_gp > 0),
    restock_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '1 hour',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(campaign_id, settlement_key, poi_key)
);

CREATE TABLE IF NOT EXISTS public.discord_economy_stock
(
    stock_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id UUID NOT NULL REFERENCES public.discord_economy_shops(shop_id) ON DELETE CASCADE,
    item_key TEXT NOT NULL,
    item_name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Goods',
    rarity TEXT NOT NULL DEFAULT 'Common',
    value_class TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    base_price_gp NUMERIC(12,2) NOT NULL CHECK(base_price_gp >= 0),
    quantity INTEGER NOT NULL DEFAULT 0 CHECK(quantity >= 0),
    target_quantity INTEGER NOT NULL DEFAULT 1 CHECK(target_quantity > 0),
    condition_percent INTEGER NOT NULL DEFAULT 100 CHECK(condition_percent BETWEEN 0 AND 100),
    item_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_kind TEXT NOT NULL DEFAULT 'catalog' CHECK(source_kind IN ('catalog','resale')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(shop_id, item_key)
);

CREATE TABLE IF NOT EXISTS public.discord_item_condition
(
    inventory_item_id UUID PRIMARY KEY REFERENCES public.discord_inventory_items(inventory_item_id) ON DELETE CASCADE,
    condition_percent INTEGER NOT NULL DEFAULT 100 CHECK(condition_percent BETWEEN 0 AND 100),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.discord_economy_transactions
(
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id UUID NOT NULL REFERENCES public.discord_campaigns(campaign_id) ON DELETE CASCADE,
    shop_id UUID NOT NULL REFERENCES public.discord_economy_shops(shop_id) ON DELETE CASCADE,
    character_id UUID NOT NULL REFERENCES public.discord_characters(character_id) ON DELETE CASCADE,
    transaction_kind TEXT NOT NULL,
    item_name TEXT NOT NULL DEFAULT '',
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price_gp NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_gp NUMERIC(12,2) NOT NULL DEFAULT 0,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.discord_blacksmith_orders
(
    order_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id UUID NOT NULL REFERENCES public.discord_campaigns(campaign_id) ON DELETE CASCADE,
    shop_id UUID NOT NULL REFERENCES public.discord_economy_shops(shop_id) ON DELETE CASCADE,
    character_id UUID NOT NULL REFERENCES public.discord_characters(character_id) ON DELETE CASCADE,
    item_name TEXT NOT NULL,
    item_description TEXT NOT NULL DEFAULT '',
    item_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    price_gp NUMERIC(12,2) NOT NULL CHECK(price_gp >= 0),
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','ready','completed','cancelled')),
    ready_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_discord_economy_stock_shop
ON public.discord_economy_stock(shop_id, category, item_name);

CREATE INDEX IF NOT EXISTS ix_discord_economy_transactions_character
ON public.discord_economy_transactions(character_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_discord_blacksmith_orders_character
ON public.discord_blacksmith_orders(character_id, status, ready_at);

ALTER TABLE public.discord_economy_shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_economy_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_item_condition ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_economy_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_blacksmith_orders ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.discord_economy_shops FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.discord_economy_stock FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.discord_item_condition FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.discord_economy_transactions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.discord_blacksmith_orders FROM PUBLIC, anon, authenticated;

GRANT ALL ON public.discord_economy_shops TO service_role;
GRANT ALL ON public.discord_economy_stock TO service_role;
GRANT ALL ON public.discord_item_condition TO service_role;
GRANT ALL ON public.discord_economy_transactions TO service_role;
GRANT ALL ON public.discord_blacksmith_orders TO service_role;

CREATE OR REPLACE FUNCTION public.discord_economy_settlement_multiplier(p_settlement_key TEXT)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE LOWER(TRIM(COALESCE(p_settlement_key,'')))
        WHEN 'greymoor-hollow' THEN 0.90
        WHEN 'stonewake-port' THEN 1.00
        WHEN 'emberfall' THEN 1.08
        WHEN 'lunareth' THEN 1.05
        WHEN 'high-bastion' THEN 1.12
        WHEN 'marrowfen' THEN 0.92
        WHEN 'silverreach' THEN 1.15
        WHEN 'duskmire-crossing' THEN 0.98
        WHEN 'frostharbor' THEN 1.18
        WHEN 'sunspire' THEN 1.06
        WHEN 'blackroot-enclave' THEN 1.10
        WHEN 'aetherfall' THEN 1.22
        ELSE 1.00
    END::NUMERIC;
$$;

CREATE OR REPLACE FUNCTION public.discord_economy_wealth_cap(p_shop_kind TEXT, p_market NUMERIC)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT ROUND((
        CASE LOWER(TRIM(COALESCE(p_shop_kind,'')))
            WHEN 'enchanter' THEN 1000
            WHEN 'smithy' THEN 600
            WHEN 'arms' THEN 600
            WHEN 'market' THEN 500
            WHEN 'alchemy' THEN 400
            WHEN 'apothecary' THEN 350
            WHEN 'general' THEN 300
            WHEN 'fletcher' THEN 250
            WHEN 'fishmarket' THEN 220
            WHEN 'ceramics' THEN 180
            ELSE 250
        END
    ) * GREATEST(0.75, LEAST(1.40, COALESCE(p_market,1))), 2);
$$;

CREATE OR REPLACE FUNCTION public.discord_economy_reputation_score(
    p_campaign_id UUID,
    p_character_id UUID
)
RETURNS INTEGER
LANGUAGE sql
STABLE
AS $$
    SELECT COALESCE(ROUND(AVG(r.score))::INTEGER, 0)
    FROM public.discord_faction_reputation r
    WHERE r.campaign_id = p_campaign_id
      AND (r.character_id = p_character_id OR LOWER(COALESCE(r.subject_type,'')) = 'party');
$$;

CREATE OR REPLACE FUNCTION public.discord_economy_reputation_label(p_score INTEGER)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE
        WHEN COALESCE(p_score,0) <= -61 THEN 'Hostile'
        WHEN COALESCE(p_score,0) <= -21 THEN 'Unfriendly'
        WHEN COALESCE(p_score,0) <= 20 THEN 'Neutral'
        WHEN COALESCE(p_score,0) <= 60 THEN 'Friendly'
        ELSE 'Allied'
    END;
$$;

CREATE OR REPLACE FUNCTION public.discord_economy_buy_reputation_multiplier(p_score INTEGER)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE
        WHEN COALESCE(p_score,0) <= -61 THEN 1.20
        WHEN COALESCE(p_score,0) <= -21 THEN 1.10
        WHEN COALESCE(p_score,0) <= 20 THEN 1.00
        WHEN COALESCE(p_score,0) <= 60 THEN 0.95
        ELSE 0.90
    END::NUMERIC;
$$;

CREATE OR REPLACE FUNCTION public.discord_economy_sell_reputation_multiplier(p_score INTEGER)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE
        WHEN COALESCE(p_score,0) <= -61 THEN 0.70
        WHEN COALESCE(p_score,0) <= -21 THEN 0.85
        WHEN COALESCE(p_score,0) <= 20 THEN 1.00
        WHEN COALESCE(p_score,0) <= 60 THEN 1.10
        ELSE 1.20
    END::NUMERIC;
$$;

CREATE OR REPLACE FUNCTION public.discord_economy_scarcity_multiplier(p_quantity INTEGER, p_target INTEGER)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT GREATEST(0.90, LEAST(1.35,
        1.35 - 0.45 * LEAST(1.0, GREATEST(0.0,
            COALESCE(p_quantity,0)::NUMERIC / GREATEST(1,COALESCE(p_target,1))))
    ));
$$;

CREATE OR REPLACE FUNCTION public.discord_economy_condition_multiplier(p_condition INTEGER)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT GREATEST(0.25, LEAST(1.00,
        0.25 + 0.75 * (COALESCE(p_condition,100)::NUMERIC / 100.0)));
$$;

CREATE OR REPLACE FUNCTION public.discord_economy_material_demand_multiplier(
    p_shop_kind TEXT,
    p_family TEXT
)
RETURNS NUMERIC
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    v_kind TEXT := LOWER(TRIM(COALESCE(p_shop_kind,'')));
    v_family TEXT := LOWER(TRIM(COALESCE(p_family,'')));
BEGIN
    IF v_family = '' THEN RETURN 1.00; END IF;
    IF v_kind IN ('market','general') THEN RETURN 1.10; END IF;

    IF v_kind IN ('smithy','arms','fletcher') AND v_family IN (
        'leather','pelt_hide','bone_horn','chitin_shell','dragon_scale',
        'dragon_scale_component','bone_reinforcement','cordage','construct_salvage','alchemical_adhesive'
    ) THEN RETURN 1.25; END IF;

    IF v_kind IN ('alchemy','apothecary','enchanter') AND v_family IN (
        'healing_herb','venom','dragon_blood','draconic_reagent','ooze_residue',
        'alchemical_adhesive','elemental_essence','elemental_infusion','ectoplasm','vial'
    ) THEN RETURN 1.25; END IF;

    IF v_kind = 'fishmarket' AND v_family IN ('monster_meat','pelt_hide','bone_horn')
    THEN RETURN 1.20; END IF;

    RETURN 1.00;
END;
$$;

CREATE OR REPLACE FUNCTION public.discord_economy_refresh_shop(p_shop_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_shop public.discord_economy_shops%ROWTYPE;
BEGIN
    SELECT * INTO v_shop
    FROM public.discord_economy_shops
    WHERE shop_id = p_shop_id
    FOR UPDATE;

    IF v_shop.shop_id IS NULL THEN
        RAISE EXCEPTION 'Dynamic shop could not be found.';
    END IF;

    IF v_shop.restock_at <= NOW() THEN
        UPDATE public.discord_economy_stock s
        SET quantity = CASE
                WHEN s.source_kind = 'catalog' THEN
                    GREATEST(s.quantity,
                        LEAST(s.target_quantity,
                            s.quantity + GREATEST(1, CEIL(s.target_quantity * 0.75)::INTEGER)))
                ELSE s.quantity
            END,
            updated_at = NOW()
        WHERE s.shop_id = p_shop_id;

        UPDATE public.discord_economy_shops
        SET wealth_gp = LEAST(wealth_cap_gp,
                ROUND(wealth_gp + (wealth_cap_gp - wealth_gp) * 0.50, 2)),
            restock_at = NOW() + INTERVAL '1 hour',
            updated_at = NOW()
        WHERE shop_id = p_shop_id;
    END IF;

    -- Resale rows do not restock. Once purchased out, remove the empty listing.
    DELETE FROM public.discord_economy_stock
    WHERE shop_id = p_shop_id
      AND source_kind = 'resale'
      AND quantity <= 0;

    UPDATE public.discord_blacksmith_orders
    SET status = 'ready'
    WHERE shop_id = p_shop_id
      AND status = 'pending'
      AND ready_at <= NOW();
END;
$$;

DROP FUNCTION IF EXISTS public.discord_economy_seed_shop(UUID,TEXT,TEXT,TEXT,TEXT,TEXT,JSONB);
CREATE OR REPLACE FUNCTION public.discord_economy_seed_shop(
    p_campaign_id UUID,
    p_settlement_key TEXT,
    p_settlement_name TEXT,
    p_poi_key TEXT,
    p_shop_name TEXT,
    p_shop_kind TEXT,
    p_catalog JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_shop_id UUID;
    v_market NUMERIC;
    v_cap NUMERIC;
    v_item JSONB;
    v_target INTEGER;
    v_initial INTEGER;
    v_key TEXT;
    v_rarity TEXT;
BEGIN
    IF p_campaign_id IS NULL THEN RAISE EXCEPTION 'Campaign is required.'; END IF;
    IF TRIM(COALESCE(p_settlement_key,'')) = '' OR TRIM(COALESCE(p_poi_key,'')) = '' THEN
        RAISE EXCEPTION 'Settlement and shop location are required.';
    END IF;
    IF p_catalog IS NULL OR jsonb_typeof(p_catalog) <> 'array' THEN
        RAISE EXCEPTION 'Trusted shop catalog must be a JSON array.';
    END IF;

    v_market := public.discord_economy_settlement_multiplier(p_settlement_key);
    v_cap := public.discord_economy_wealth_cap(p_shop_kind, v_market);

    INSERT INTO public.discord_economy_shops(
        campaign_id, settlement_key, settlement_name, poi_key, shop_name, shop_kind,
        settlement_multiplier, wealth_gp, wealth_cap_gp, restock_at)
    VALUES(
        p_campaign_id, LOWER(TRIM(p_settlement_key)), TRIM(p_settlement_name),
        LOWER(TRIM(p_poi_key)), TRIM(p_shop_name), LOWER(TRIM(p_shop_kind)),
        v_market, ROUND(v_cap * 0.70,2), v_cap, NOW() + INTERVAL '1 hour')
    ON CONFLICT(campaign_id,settlement_key,poi_key) DO UPDATE SET
        settlement_name = EXCLUDED.settlement_name,
        shop_name = EXCLUDED.shop_name,
        shop_kind = EXCLUDED.shop_kind,
        settlement_multiplier = EXCLUDED.settlement_multiplier,
        wealth_cap_gp = EXCLUDED.wealth_cap_gp,
        updated_at = NOW()
    RETURNING shop_id INTO v_shop_id;

    FOR v_item IN SELECT value FROM jsonb_array_elements(p_catalog) LOOP
        v_key := TRIM(COALESCE(v_item->>'itemKey',''));
        IF v_key = '' THEN CONTINUE; END IF;
        v_rarity := LOWER(TRIM(COALESCE(v_item->>'rarity','common')));

        v_target := CASE v_rarity
            WHEN 'artifact' THEN 1
            WHEN 'legendary' THEN 1
            WHEN 'very rare' THEN 1
            WHEN 'rare' THEN 2
            WHEN 'uncommon' THEN 3
            ELSE 5 + MOD(ABS(hashtext(v_shop_id::TEXT || ':' || v_key)::BIGINT),4)::INTEGER
        END;

        v_initial := CASE
            WHEN v_rarity IN ('rare','very rare','legendary','artifact')
                THEN MOD(ABS(hashtext(v_shop_id::TEXT || ':rare:' || v_key)::BIGINT),v_target + 1)::INTEGER
            ELSE GREATEST(1,
                MOD(ABS(hashtext(v_shop_id::TEXT || ':stock:' || v_key)::BIGINT),v_target + 1)::INTEGER)
        END;

        INSERT INTO public.discord_economy_stock(
            shop_id,item_key,item_name,category,rarity,value_class,description,
            base_price_gp,quantity,target_quantity,condition_percent,item_data,source_kind)
        VALUES(
            v_shop_id,
            v_key,
            TRIM(COALESCE(v_item->>'itemName','Unknown Item')),
            COALESCE(v_item->>'category','Goods'),
            COALESCE(v_item->>'rarity','Common'),
            COALESCE(v_item->>'valueClass',''),
            COALESCE(v_item->>'description',''),
            ROUND(GREATEST(0.01,COALESCE((v_item->>'basePriceGp')::NUMERIC,0.01)),2),
            v_initial,
            v_target,
            100,
            '{}'::jsonb,
            'catalog')
        ON CONFLICT(shop_id,item_key) DO UPDATE SET
            item_name = EXCLUDED.item_name,
            category = EXCLUDED.category,
            rarity = EXCLUDED.rarity,
            value_class = EXCLUDED.value_class,
            description = EXCLUDED.description,
            base_price_gp = EXCLUDED.base_price_gp,
            target_quantity = EXCLUDED.target_quantity,
            updated_at = NOW();
    END LOOP;

    PERFORM public.discord_economy_refresh_shop(v_shop_id);
    RETURN jsonb_build_object('success',TRUE,'shopId',v_shop_id);
END;
$$;

DROP FUNCTION IF EXISTS public.discord_economy_get_shop(UUID,UUID,UUID,JSONB,JSONB);
CREATE OR REPLACE FUNCTION public.discord_economy_get_shop(
    p_player_id UUID,
    p_campaign_id UUID,
    p_shop_id UUID,
    p_sell_items JSONB,
    p_service_items JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_active_player UUID;
    v_character RECORD;
    v_shop public.discord_economy_shops%ROWTYPE;
    v_rep INTEGER;
    v_buy_rep NUMERIC;
    v_sell_rep NUMERIC;
    v_items JSONB := '[]'::jsonb;
    v_sells JSONB := '[]'::jsonb;
    v_services JSONB := '{}'::jsonb;
    v_orders JSONB := '[]'::jsonb;
    v_commissions JSONB := '[]'::jsonb;
    v_repairs JSONB := '[]'::jsonb;
    v_improvements JSONB := '[]'::jsonb;
    v_stock RECORD;
    v_sell JSONB;
    v_service JSONB;
    v_condition INTEGER;
    v_price NUMERIC;
    v_demand NUMERIC;
    v_can_sell BOOLEAN;
    v_reason TEXT;
    v_base NUMERIC;
    v_improvement INTEGER;
    v_item_type TEXT;
BEGIN
    IF NOT EXISTS(
        SELECT 1 FROM public.discord_campaign_members m
        WHERE m.campaign_id = p_campaign_id AND m.player_id = p_player_id
    ) THEN RAISE EXCEPTION 'You are not a member of this campaign.'; END IF;

    v_active_player := public.discord_resolve_active_player(p_player_id,p_campaign_id);
    SELECT c.* INTO v_character
    FROM public.discord_characters c
    WHERE c.campaign_id = p_campaign_id AND c.player_id = v_active_player
    LIMIT 1;
    IF v_character.character_id IS NULL THEN
        RAISE EXCEPTION 'Active campaign character could not be found.';
    END IF;

    SELECT * INTO v_shop
    FROM public.discord_economy_shops
    WHERE shop_id = p_shop_id AND campaign_id = p_campaign_id;
    IF v_shop.shop_id IS NULL THEN RAISE EXCEPTION 'Dynamic shop could not be found.'; END IF;

    IF NOT EXISTS(
        SELECT 1 FROM public.discord_player_settlement_locations l
        WHERE l.campaign_id = p_campaign_id
          AND l.player_id = p_player_id
          AND LOWER(TRIM(l.settlement_key)) = LOWER(TRIM(v_shop.settlement_key))
          AND LOWER(TRIM(l.poi_key)) = LOWER(TRIM(v_shop.poi_key))
    ) THEN RAISE EXCEPTION 'Your character is not currently at that shop.'; END IF;

    PERFORM public.discord_economy_refresh_shop(v_shop.shop_id);
    SELECT * INTO v_shop FROM public.discord_economy_shops WHERE shop_id = p_shop_id;

    v_rep := public.discord_economy_reputation_score(p_campaign_id,v_character.character_id);
    v_buy_rep := public.discord_economy_buy_reputation_multiplier(v_rep);
    v_sell_rep := public.discord_economy_sell_reputation_multiplier(v_rep);

    FOR v_stock IN
        SELECT * FROM public.discord_economy_stock
        WHERE shop_id = v_shop.shop_id
        ORDER BY category,item_name,condition_percent DESC
    LOOP
        v_price := ROUND(GREATEST(0.01,
            v_stock.base_price_gp
            * v_shop.settlement_multiplier
            * public.discord_economy_scarcity_multiplier(v_stock.quantity,v_stock.target_quantity)
            * v_buy_rep
            * (0.55 + 0.45 * (v_stock.condition_percent::NUMERIC / 100.0))
        ),2);

        v_items := v_items || jsonb_build_array(jsonb_build_object(
            'itemKey',v_stock.stock_id::TEXT,
            'stockId',v_stock.stock_id,
            'catalogItemKey',CASE WHEN v_stock.source_kind='catalog' THEN v_stock.item_key ELSE '' END,
            'itemName',v_stock.item_name,
            'category',v_stock.category,
            'rarity',v_stock.rarity,
            'valueClass',v_stock.value_class,
            'description',v_stock.description,
            'basePriceGp',v_stock.base_price_gp,
            'priceGp',v_price,
            'quantityAvailable',v_stock.quantity,
            'targetQuantity',v_stock.target_quantity,
            'conditionPercent',v_stock.condition_percent,
            'sourceKind',v_stock.source_kind,
            'scarcityLabel',CASE
                WHEN v_stock.quantity <= 0 THEN 'Out of Stock'
                WHEN v_stock.quantity * 4 <= v_stock.target_quantity THEN 'Very Scarce'
                WHEN v_stock.quantity * 2 <= v_stock.target_quantity THEN 'Scarce'
                WHEN v_stock.quantity >= v_stock.target_quantity THEN 'Well Stocked'
                ELSE 'Available'
            END
        ));
    END LOOP;

    IF p_sell_items IS NOT NULL AND jsonb_typeof(p_sell_items) = 'array' THEN
        FOR v_sell IN SELECT value FROM jsonb_array_elements(p_sell_items) LOOP
            v_condition := COALESCE((
                SELECT c.condition_percent
                FROM public.discord_item_condition c
                WHERE c.inventory_item_id = (v_sell->>'inventoryItemId')::UUID
            ),100);

            v_can_sell := COALESCE((v_sell->>'canSell')::BOOLEAN,FALSE);
            v_reason := COALESCE(v_sell->>'reason','');
            v_base := GREATEST(0,COALESCE((v_sell->>'baseValueGp')::NUMERIC,0));
            v_demand := public.discord_economy_material_demand_multiplier(
                v_shop.shop_kind,COALESCE(v_sell->>'craftingFamily',''));

            v_price := ROUND(GREATEST(0.01,
                v_base * 0.50
                * v_shop.settlement_multiplier
                * v_sell_rep
                * v_demand
                * public.discord_economy_condition_multiplier(v_condition)
            ),2);

            IF v_shop.wealth_gp < v_price THEN
                v_can_sell := FALSE;
                v_reason := 'This merchant does not currently have enough cash for even one unit.';
            END IF;

            v_sells := v_sells || jsonb_build_array(
                v_sell || jsonb_build_object(
                    'conditionPercent',v_condition,
                    'unitPriceGp',CASE WHEN v_can_sell THEN v_price ELSE 0 END,
                    'canSell',v_can_sell,
                    'reason',v_reason,
                    'demandMultiplier',v_demand,
                    'maxMerchantQuantity',CASE
                        WHEN v_can_sell THEN GREATEST(0,FLOOR(v_shop.wealth_gp / v_price)::INTEGER)
                        ELSE 0
                    END
                )
            );
        END LOOP;
    END IF;

    IF v_shop.shop_kind IN ('smithy','arms') THEN
        IF p_service_items IS NOT NULL AND jsonb_typeof(p_service_items) = 'array' THEN
            FOR v_service IN SELECT value FROM jsonb_array_elements(p_service_items) LOOP
                v_condition := COALESCE((
                    SELECT c.condition_percent
                    FROM public.discord_item_condition c
                    WHERE c.inventory_item_id = (v_service->>'inventoryItemId')::UUID
                ),100);
                v_base := GREATEST(0.01,COALESCE((v_service->>'baseValueGp')::NUMERIC,0.01));
                v_improvement := GREATEST(0,COALESCE((v_service->>'improvementLevel')::INTEGER,0));
                v_item_type := LOWER(COALESCE(v_service->>'itemType',''));

                IF v_condition < 100 THEN
                    v_price := ROUND(GREATEST(0.50,
                        v_base * ((100-v_condition)::NUMERIC / 100.0) * 0.35
                        * v_shop.settlement_multiplier * v_buy_rep),2);
                    v_repairs := v_repairs || jsonb_build_array(v_service || jsonb_build_object(
                        'conditionPercent',v_condition,
                        'servicePriceGp',v_price,
                        'serviceType','repair'));
                END IF;

                IF v_improvement < 1 AND (
                    v_item_type LIKE '%weapon%'
                    OR v_item_type LIKE '%armor%'
                    OR v_item_type LIKE '%armour%'
                    OR v_item_type LIKE '%shield%'
                    OR v_item_type LIKE '%helmet%'
                ) THEN
                    v_price := ROUND(GREATEST(25.00,v_base * 0.40)
                        * v_shop.settlement_multiplier * v_buy_rep,2);
                    v_improvements := v_improvements || jsonb_build_array(v_service || jsonb_build_object(
                        'servicePriceGp',v_price,
                        'serviceType','improve',
                        'improvementName','Masterwork +1'));
                END IF;
            END LOOP;
        END IF;

        SELECT COALESCE(jsonb_agg(jsonb_build_object(
            'stockId',s.stock_id,
            'itemName',s.item_name,
            'category',s.category,
            'basePriceGp',s.base_price_gp,
            'commissionPriceGp',ROUND(GREATEST(0.01,
                s.base_price_gp * v_shop.settlement_multiplier * v_buy_rep * 1.25),2),
            'description',s.description,
            'rarity',s.rarity
        ) ORDER BY s.category,s.item_name),'[]'::jsonb)
        INTO v_commissions
        FROM public.discord_economy_stock s
        WHERE s.shop_id = v_shop.shop_id AND s.source_kind = 'catalog';

        SELECT COALESCE(jsonb_agg(jsonb_build_object(
            'orderId',o.order_id,
            'itemName',o.item_name,
            'priceGp',o.price_gp,
            'status',CASE WHEN o.status='pending' AND o.ready_at<=NOW() THEN 'ready' ELSE o.status END,
            'readyAt',o.ready_at,
            'canClaim',(o.status='ready' OR (o.status='pending' AND o.ready_at<=NOW()))
        ) ORDER BY o.created_at DESC),'[]'::jsonb)
        INTO v_orders
        FROM public.discord_blacksmith_orders o
        WHERE o.campaign_id = p_campaign_id
          AND o.shop_id = v_shop.shop_id
          AND o.character_id = v_character.character_id
          AND o.status IN ('pending','ready');

        v_services := jsonb_build_object(
            'available',TRUE,
            'repairs',v_repairs,
            'improvements',v_improvements,
            'commissions',v_commissions,
            'orders',v_orders
        );
    ELSE
        v_services := jsonb_build_object('available',FALSE);
    END IF;

    RETURN jsonb_build_object(
        'success',TRUE,
        'dynamicEconomy',TRUE,
        'shopId',v_shop.shop_id,
        'settlementName',v_shop.settlement_name,
        'poiKey',v_shop.poi_key,
        'shopName',v_shop.shop_name,
        'shopKind',v_shop.shop_kind,
        'gold',ROUND(COALESCE(v_character.gold,0),2),
        'merchantWealthGp',v_shop.wealth_gp,
        'merchantWealthCapGp',v_shop.wealth_cap_gp,
        'settlementMultiplier',v_shop.settlement_multiplier,
        'reputationScore',v_rep,
        'reputationTier',public.discord_economy_reputation_label(v_rep),
        'restockAt',v_shop.restock_at,
        'items',v_items,
        'sellItems',v_sells,
        'services',v_services
    );
END;
$$;

DROP FUNCTION IF EXISTS public.discord_economy_buy(UUID,UUID,UUID,INTEGER);
CREATE OR REPLACE FUNCTION public.discord_economy_buy(
    p_player_id UUID,
    p_campaign_id UUID,
    p_stock_id UUID,
    p_quantity INTEGER
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_active_player UUID;
    v_character RECORD;
    v_stock public.discord_economy_stock%ROWTYPE;
    v_shop public.discord_economy_shops%ROWTYPE;
    v_rep INTEGER;
    v_unit NUMERIC;
    v_total NUMERIC;
    v_remaining_gold NUMERIC;
    v_inventory_id UUID;
BEGIN
    IF COALESCE(p_quantity,0) < 1 OR p_quantity > 100 THEN
        RAISE EXCEPTION 'Purchase quantity must be between 1 and 100.';
    END IF;

    -- Resolve the stock's shop first without taking the stock-row lock. We then lock
    -- the shop before stock so all Build 6.29 transaction paths use shop -> stock
    -- lock ordering and avoid cross-request deadlocks during restock.
    SELECT * INTO v_stock
    FROM public.discord_economy_stock
    WHERE stock_id = p_stock_id;
    IF v_stock.stock_id IS NULL THEN RAISE EXCEPTION 'Shop stock item could not be found.'; END IF;

    SELECT * INTO v_shop
    FROM public.discord_economy_shops
    WHERE shop_id = v_stock.shop_id AND campaign_id = p_campaign_id
    FOR UPDATE;
    IF v_shop.shop_id IS NULL THEN RAISE EXCEPTION 'Dynamic shop could not be found.'; END IF;

    IF NOT EXISTS(
        SELECT 1 FROM public.discord_campaign_members m
        WHERE m.campaign_id = p_campaign_id AND m.player_id = p_player_id
    ) THEN RAISE EXCEPTION 'You are not a member of this campaign.'; END IF;

    IF NOT EXISTS(
        SELECT 1 FROM public.discord_player_settlement_locations l
        WHERE l.campaign_id = p_campaign_id AND l.player_id = p_player_id
          AND LOWER(TRIM(l.settlement_key)) = LOWER(TRIM(v_shop.settlement_key))
          AND LOWER(TRIM(l.poi_key)) = LOWER(TRIM(v_shop.poi_key))
    ) THEN RAISE EXCEPTION 'Your character is not currently at that shop.'; END IF;

    PERFORM public.discord_economy_refresh_shop(v_shop.shop_id);
    SELECT * INTO v_stock FROM public.discord_economy_stock WHERE stock_id = p_stock_id FOR UPDATE;
    SELECT * INTO v_shop FROM public.discord_economy_shops WHERE shop_id = v_stock.shop_id FOR UPDATE;

    IF v_stock.quantity < p_quantity THEN
        RAISE EXCEPTION 'Only % unit(s) remain in stock.',v_stock.quantity;
    END IF;

    v_active_player := public.discord_resolve_active_player(p_player_id,p_campaign_id);
    SELECT c.* INTO v_character
    FROM public.discord_characters c
    WHERE c.campaign_id = p_campaign_id AND c.player_id = v_active_player
    LIMIT 1 FOR UPDATE;
    IF v_character.character_id IS NULL THEN RAISE EXCEPTION 'Active campaign character could not be found.'; END IF;
    IF LOWER(COALESCE(v_character.life_state,'alive')) = 'dead' THEN
        RAISE EXCEPTION 'A dead character cannot shop.';
    END IF;

    v_rep := public.discord_economy_reputation_score(p_campaign_id,v_character.character_id);
    v_unit := ROUND(GREATEST(0.01,
        v_stock.base_price_gp
        * v_shop.settlement_multiplier
        * public.discord_economy_scarcity_multiplier(v_stock.quantity,v_stock.target_quantity)
        * public.discord_economy_buy_reputation_multiplier(v_rep)
        * (0.55 + 0.45 * (v_stock.condition_percent::NUMERIC / 100.0))
    ),2);
    v_total := ROUND(v_unit * p_quantity,2);

    v_remaining_gold := public.discord_adjust_currency_value(
        v_character.character_id,p_campaign_id,-v_total);

    PERFORM public.discord_gm_add_inventory_item(
        v_character.character_id,
        p_campaign_id,
        v_stock.item_name,
        p_quantity,
        v_stock.description,
        'Purchased from ' || v_shop.shop_name,
        CASE WHEN v_stock.condition_percent < 100 THEN 'Used merchandise' ELSE 'Dynamic economy purchase' END
    );

    UPDATE public.discord_economy_stock
    SET quantity = quantity - p_quantity, updated_at = NOW()
    WHERE stock_id = v_stock.stock_id;

    UPDATE public.discord_economy_shops
    SET wealth_gp = LEAST(wealth_cap_gp * 1.50, ROUND(wealth_gp + v_total,2)),
        updated_at = NOW()
    WHERE shop_id = v_shop.shop_id;

    SELECT i.inventory_item_id INTO v_inventory_id
    FROM public.discord_inventory_items i
    WHERE i.character_id = v_character.character_id
      AND LOWER(TRIM(i.item_name)) = LOWER(TRIM(v_stock.item_name))
    ORDER BY i.updated_at DESC,i.created_at DESC,i.inventory_item_id DESC
    LIMIT 1;

    IF v_inventory_id IS NOT NULL AND v_stock.item_data <> '{}'::jsonb THEN
        UPDATE public.discord_inventory_items
        SET item_data = COALESCE(item_data,'{}'::jsonb) || v_stock.item_data,
            updated_at = NOW()
        WHERE inventory_item_id = v_inventory_id;
    END IF;

    IF v_inventory_id IS NOT NULL AND v_stock.condition_percent < 100 THEN
        INSERT INTO public.discord_item_condition(inventory_item_id,condition_percent)
        VALUES(v_inventory_id,v_stock.condition_percent)
        ON CONFLICT(inventory_item_id) DO UPDATE
        SET condition_percent = EXCLUDED.condition_percent,
            updated_at = NOW();
    END IF;

    INSERT INTO public.discord_economy_transactions(
        campaign_id,shop_id,character_id,transaction_kind,item_name,quantity,
        unit_price_gp,total_gp,details)
    VALUES(
        p_campaign_id,v_shop.shop_id,v_character.character_id,'buy',v_stock.item_name,
        p_quantity,v_unit,v_total,
        jsonb_build_object('stockId',v_stock.stock_id,
                           'conditionPercent',v_stock.condition_percent,
                           'reputationScore',v_rep));

    RETURN jsonb_build_object(
        'success',TRUE,
        'itemName',v_stock.item_name,
        'quantityPurchased',p_quantity,
        'unitPriceGp',v_unit,
        'totalPriceGp',v_total,
        'remainingGold',v_remaining_gold,
        'message','Purchased ' || p_quantity::TEXT || ' × ' || v_stock.item_name || ' for ' || v_total::TEXT || ' GP.'
    );
END;
$$;

DROP FUNCTION IF EXISTS public.discord_economy_sell(UUID,UUID,UUID,INTEGER,BOOLEAN,TEXT,TEXT,TEXT,NUMERIC,TEXT,JSONB);
CREATE OR REPLACE FUNCTION public.discord_economy_sell(
    p_player_id UUID,
    p_campaign_id UUID,
    p_inventory_item_id UUID,
    p_quantity INTEGER,
    p_can_sell BOOLEAN,
    p_item_name TEXT,
    p_category TEXT,
    p_rarity TEXT,
    p_base_value_gp NUMERIC,
    p_crafting_family TEXT,
    p_item_data JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_active_player UUID;
    v_character RECORD;
    v_inventory RECORD;
    v_location RECORD;
    v_shop public.discord_economy_shops%ROWTYPE;
    v_condition INTEGER;
    v_rep INTEGER;
    v_demand NUMERIC;
    v_unit NUMERIC;
    v_total NUMERIC;
    v_remaining INTEGER;
    v_remaining_gold NUMERIC;
    v_resale_key TEXT;
BEGIN
    IF NOT EXISTS(
        SELECT 1 FROM public.discord_campaign_members m
        WHERE m.campaign_id = p_campaign_id AND m.player_id = p_player_id
    ) THEN RAISE EXCEPTION 'You are not a member of this campaign.'; END IF;

    IF NOT COALESCE(p_can_sell,FALSE) THEN
        RAISE EXCEPTION 'This merchant will not buy that item.';
    END IF;
    IF COALESCE(p_quantity,0) < 1 OR p_quantity > 1000 THEN
        RAISE EXCEPTION 'Sell quantity must be between 1 and 1000.';
    END IF;
    IF COALESCE(p_base_value_gp,0) <= 0 THEN
        RAISE EXCEPTION 'Item has no authoritative resale value.';
    END IF;

    SELECT l.* INTO v_location
    FROM public.discord_player_settlement_locations l
    WHERE l.campaign_id = p_campaign_id AND l.player_id = p_player_id;
    IF v_location.poi_key IS NULL THEN
        RAISE EXCEPTION 'Your character is not currently at a shop.';
    END IF;

    SELECT * INTO v_shop
    FROM public.discord_economy_shops
    WHERE campaign_id = p_campaign_id
      AND LOWER(settlement_key) = LOWER(v_location.settlement_key)
      AND LOWER(poi_key) = LOWER(v_location.poi_key)
    LIMIT 1
    FOR UPDATE;
    IF v_shop.shop_id IS NULL THEN
        RAISE EXCEPTION 'Dynamic shop could not be found.';
    END IF;

    PERFORM public.discord_economy_refresh_shop(v_shop.shop_id);
    SELECT * INTO v_shop
    FROM public.discord_economy_shops
    WHERE shop_id = v_shop.shop_id
    FOR UPDATE;

    v_active_player := public.discord_resolve_active_player(p_player_id,p_campaign_id);
    SELECT c.* INTO v_character
    FROM public.discord_characters c
    WHERE c.campaign_id = p_campaign_id AND c.player_id = v_active_player
    LIMIT 1
    FOR UPDATE;
    IF v_character.character_id IS NULL THEN
        RAISE EXCEPTION 'Active campaign character could not be found.';
    END IF;
    IF LOWER(COALESCE(v_character.life_state,'alive')) = 'dead' THEN
        RAISE EXCEPTION 'A dead character cannot sell items.';
    END IF;

    SELECT i.inventory_item_id,i.item_name,i.quantity,i.equipped,i.attuned,i.item_data
    INTO v_inventory
    FROM public.discord_inventory_items i
    WHERE i.inventory_item_id = p_inventory_item_id
      AND i.character_id = v_character.character_id
    FOR UPDATE;
    IF v_inventory.inventory_item_id IS NULL THEN
        RAISE EXCEPTION 'Inventory item could not be found.';
    END IF;
    IF v_inventory.quantity < p_quantity THEN
        RAISE EXCEPTION 'You do not carry that many.';
    END IF;
    IF COALESCE(v_inventory.equipped,FALSE) THEN
        RAISE EXCEPTION 'Unequip this item before selling it.';
    END IF;
    IF COALESCE(v_inventory.attuned,FALSE) THEN
        RAISE EXCEPTION 'End attunement before selling it.';
    END IF;
    IF LOWER(TRIM(v_inventory.item_name)) <> LOWER(TRIM(p_item_name)) THEN
        RAISE EXCEPTION 'Inventory item changed before sale.';
    END IF;

    v_condition := COALESCE((
        SELECT c.condition_percent
        FROM public.discord_item_condition c
        WHERE c.inventory_item_id = p_inventory_item_id
    ),100);
    v_rep := public.discord_economy_reputation_score(p_campaign_id,v_character.character_id);
    v_demand := public.discord_economy_material_demand_multiplier(v_shop.shop_kind,p_crafting_family);

    v_unit := ROUND(GREATEST(0.01,
        p_base_value_gp
        * 0.50
        * v_shop.settlement_multiplier
        * public.discord_economy_sell_reputation_multiplier(v_rep)
        * v_demand
        * public.discord_economy_condition_multiplier(v_condition)
    ),2);
    v_total := ROUND(v_unit * p_quantity,2);

    IF v_shop.wealth_gp < v_total THEN
        RAISE EXCEPTION 'This merchant has only % GP available and cannot afford % GP for that sale.',
            v_shop.wealth_gp,v_total;
    END IF;

    -- The inventory row was locked and verified against the active character above.
    -- Remove it directly so Solo-party active-character switching remains authoritative
    -- even though the legacy pre-Solo removal RPC was created before Build 6.17.
    IF p_quantity = v_inventory.quantity THEN
        DELETE FROM public.discord_inventory_items
        WHERE inventory_item_id = p_inventory_item_id;
        v_remaining := 0;
    ELSE
        UPDATE public.discord_inventory_items
        SET quantity = quantity - p_quantity,
            updated_at = NOW()
        WHERE inventory_item_id = p_inventory_item_id
        RETURNING quantity INTO v_remaining;
    END IF;

    v_remaining_gold := public.discord_adjust_currency_value(
        v_character.character_id,p_campaign_id,v_total);

    UPDATE public.discord_economy_shops
    SET wealth_gp = GREATEST(0,ROUND(wealth_gp - v_total,2)),
        updated_at = NOW()
    WHERE shop_id = v_shop.shop_id;

    v_resale_key := 'resale-' || REPLACE(gen_random_uuid()::TEXT,'-','');
    INSERT INTO public.discord_economy_stock(
        shop_id,item_key,item_name,category,rarity,value_class,description,
        base_price_gp,quantity,target_quantity,condition_percent,item_data,source_kind)
    VALUES(
        v_shop.shop_id,
        v_resale_key,
        p_item_name,
        COALESCE(NULLIF(TRIM(p_category),''),'Used Goods'),
        COALESCE(NULLIF(TRIM(p_rarity),''),'Common'),
        'Resale',
        'Previously owned merchandise sold to ' || v_shop.shop_name || '.',
        ROUND(GREATEST(0.01,p_base_value_gp),2),
        p_quantity,
        GREATEST(1,p_quantity),
        v_condition,
        COALESCE(p_item_data,'{}'::jsonb),
        'resale');

    INSERT INTO public.discord_economy_transactions(
        campaign_id,shop_id,character_id,transaction_kind,item_name,quantity,
        unit_price_gp,total_gp,details)
    VALUES(
        p_campaign_id,v_shop.shop_id,v_character.character_id,'sell',p_item_name,p_quantity,
        v_unit,v_total,jsonb_build_object(
            'conditionPercent',v_condition,
            'reputationScore',v_rep,
            'craftingFamily',COALESCE(p_crafting_family,''),
            'demandMultiplier',v_demand));

    RETURN jsonb_build_object(
        'success',TRUE,
        'itemName',p_item_name,
        'quantitySold',p_quantity,
        'quantityRemaining',v_remaining,
        'unitPriceGp',v_unit,
        'totalPriceGp',v_total,
        'remainingGold',v_remaining_gold,
        'message','Sold ' || p_quantity::TEXT || ' × ' || p_item_name || ' for ' || v_total::TEXT || ' GP.'
    );
END;
$$;

DROP FUNCTION IF EXISTS public.discord_economy_blacksmith_service(UUID,UUID,TEXT,UUID,TEXT,TEXT,NUMERIC,UUID);
CREATE OR REPLACE FUNCTION public.discord_economy_blacksmith_service(
    p_player_id UUID,
    p_campaign_id UUID,
    p_service_type TEXT,
    p_inventory_item_id UUID,
    p_item_name TEXT,
    p_item_type TEXT,
    p_base_value_gp NUMERIC,
    p_commission_stock_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_location RECORD;
    v_shop public.discord_economy_shops%ROWTYPE;
    v_active_player UUID;
    v_character RECORD;
    v_inventory RECORD;
    v_condition INTEGER;
    v_improvement INTEGER;
    v_rep INTEGER;
    v_price NUMERIC;
    v_remaining_gold NUMERIC;
    v_type TEXT := LOWER(TRIM(COALESCE(p_service_type,'')));
    v_item_type TEXT := LOWER(TRIM(COALESCE(p_item_type,'')));
    v_order_id UUID;
    v_stock public.discord_economy_stock%ROWTYPE;
BEGIN
    IF NOT EXISTS(
        SELECT 1 FROM public.discord_campaign_members m
        WHERE m.campaign_id = p_campaign_id AND m.player_id = p_player_id
    ) THEN RAISE EXCEPTION 'You are not a member of this campaign.'; END IF;

    SELECT l.* INTO v_location
    FROM public.discord_player_settlement_locations l
    WHERE l.campaign_id = p_campaign_id AND l.player_id = p_player_id;
    IF v_location.poi_key IS NULL THEN
        RAISE EXCEPTION 'Your character is not currently at a shop.';
    END IF;

    SELECT * INTO v_shop
    FROM public.discord_economy_shops
    WHERE campaign_id = p_campaign_id
      AND LOWER(settlement_key) = LOWER(v_location.settlement_key)
      AND LOWER(poi_key) = LOWER(v_location.poi_key)
    LIMIT 1
    FOR UPDATE;
    IF v_shop.shop_id IS NULL THEN
        RAISE EXCEPTION 'Dynamic shop could not be found.';
    END IF;
    IF v_shop.shop_kind NOT IN ('smithy','arms') THEN
        RAISE EXCEPTION 'This merchant does not provide blacksmith services.';
    END IF;

    PERFORM public.discord_economy_refresh_shop(v_shop.shop_id);
    SELECT * INTO v_shop
    FROM public.discord_economy_shops
    WHERE shop_id = v_shop.shop_id
    FOR UPDATE;

    v_active_player := public.discord_resolve_active_player(p_player_id,p_campaign_id);
    SELECT c.* INTO v_character
    FROM public.discord_characters c
    WHERE c.campaign_id = p_campaign_id AND c.player_id = v_active_player
    LIMIT 1
    FOR UPDATE;
    IF v_character.character_id IS NULL THEN
        RAISE EXCEPTION 'Active campaign character could not be found.';
    END IF;
    IF LOWER(COALESCE(v_character.life_state,'alive')) = 'dead' THEN
        RAISE EXCEPTION 'A dead character cannot use blacksmith services.';
    END IF;

    v_rep := public.discord_economy_reputation_score(p_campaign_id,v_character.character_id);

    IF v_type = 'commission' THEN
        IF p_commission_stock_id IS NULL THEN
            RAISE EXCEPTION 'Choose an item to commission.';
        END IF;

        SELECT * INTO v_stock
        FROM public.discord_economy_stock
        WHERE stock_id = p_commission_stock_id
          AND shop_id = v_shop.shop_id
          AND source_kind = 'catalog';
        IF v_stock.stock_id IS NULL THEN
            RAISE EXCEPTION 'That item is not in this smith''s trusted commission catalog.';
        END IF;

        v_price := ROUND(GREATEST(0.01,
            v_stock.base_price_gp
            * v_shop.settlement_multiplier
            * public.discord_economy_buy_reputation_multiplier(v_rep)
            * 1.25
        ),2);

        v_remaining_gold := public.discord_adjust_currency_value(
            v_character.character_id,p_campaign_id,-v_price);

        INSERT INTO public.discord_blacksmith_orders(
            campaign_id,shop_id,character_id,item_name,item_description,item_data,
            price_gp,status,ready_at)
        VALUES(
            p_campaign_id,
            v_shop.shop_id,
            v_character.character_id,
            v_stock.item_name,
            v_stock.description,
            COALESCE(v_stock.item_data,'{}'::jsonb) || jsonb_build_object(
                'commissioned',TRUE,
                'commissioned_from',v_shop.shop_name),
            v_price,
            'pending',
            NOW() + INTERVAL '20 minutes')
        RETURNING order_id INTO v_order_id;

        UPDATE public.discord_economy_shops
        SET wealth_gp = LEAST(wealth_cap_gp * 1.50,ROUND(wealth_gp + v_price,2)),
            updated_at = NOW()
        WHERE shop_id = v_shop.shop_id;

        INSERT INTO public.discord_economy_transactions(
            campaign_id,shop_id,character_id,transaction_kind,item_name,quantity,
            unit_price_gp,total_gp,details)
        VALUES(
            p_campaign_id,v_shop.shop_id,v_character.character_id,'commission',v_stock.item_name,1,
            v_price,v_price,jsonb_build_object('orderId',v_order_id,'readyMinutes',20));

        RETURN jsonb_build_object(
            'success',TRUE,
            'serviceType','commission',
            'orderId',v_order_id,
            'itemName',v_stock.item_name,
            'priceGp',v_price,
            'remainingGold',v_remaining_gold,
            'readyAt',NOW() + INTERVAL '20 minutes',
            'message','Commission placed for ' || v_stock.item_name || '. It will be ready in about 20 minutes.'
        );
    END IF;

    IF p_inventory_item_id IS NULL THEN
        RAISE EXCEPTION 'Choose an inventory item for this service.';
    END IF;

    SELECT i.inventory_item_id,i.item_name,i.item_data,i.equipped
    INTO v_inventory
    FROM public.discord_inventory_items i
    WHERE i.inventory_item_id = p_inventory_item_id
      AND i.character_id = v_character.character_id
    FOR UPDATE;
    IF v_inventory.inventory_item_id IS NULL THEN
        RAISE EXCEPTION 'Inventory item could not be found.';
    END IF;
    IF LOWER(TRIM(v_inventory.item_name)) <> LOWER(TRIM(COALESCE(p_item_name,''))) THEN
        RAISE EXCEPTION 'Inventory item changed before service.';
    END IF;

    v_condition := COALESCE((
        SELECT c.condition_percent
        FROM public.discord_item_condition c
        WHERE c.inventory_item_id = p_inventory_item_id
    ),100);
    v_improvement := GREATEST(0,COALESCE((v_inventory.item_data->>'economy_improvement_level')::INTEGER,0));

    IF v_type = 'repair' THEN
        IF v_condition >= 100 THEN
            RAISE EXCEPTION 'This item is already in full condition.';
        END IF;

        v_price := ROUND(GREATEST(0.50,
            GREATEST(0.01,COALESCE(p_base_value_gp,0.01))
            * ((100-v_condition)::NUMERIC / 100.0)
            * 0.35
            * v_shop.settlement_multiplier
            * public.discord_economy_buy_reputation_multiplier(v_rep)
        ),2);

        v_remaining_gold := public.discord_adjust_currency_value(
            v_character.character_id,p_campaign_id,-v_price);

        INSERT INTO public.discord_item_condition(inventory_item_id,condition_percent)
        VALUES(p_inventory_item_id,100)
        ON CONFLICT(inventory_item_id) DO UPDATE
        SET condition_percent = 100,
            updated_at = NOW();

        UPDATE public.discord_economy_shops
        SET wealth_gp = LEAST(wealth_cap_gp * 1.50,ROUND(wealth_gp + v_price,2)),
            updated_at = NOW()
        WHERE shop_id = v_shop.shop_id;

        INSERT INTO public.discord_economy_transactions(
            campaign_id,shop_id,character_id,transaction_kind,item_name,quantity,
            unit_price_gp,total_gp,details)
        VALUES(
            p_campaign_id,v_shop.shop_id,v_character.character_id,'repair',v_inventory.item_name,1,
            v_price,v_price,jsonb_build_object('conditionBefore',v_condition,'conditionAfter',100));

        RETURN jsonb_build_object(
            'success',TRUE,
            'serviceType','repair',
            'itemName',v_inventory.item_name,
            'priceGp',v_price,
            'remainingGold',v_remaining_gold,
            'message',v_inventory.item_name || ' repaired to 100% condition.'
        );
    ELSIF v_type = 'improve' THEN
        IF v_improvement >= 1 THEN
            RAISE EXCEPTION 'This item already has its Build 6.29 Masterwork improvement.';
        END IF;
        IF NOT(
            v_item_type LIKE '%weapon%'
            OR v_item_type LIKE '%armor%'
            OR v_item_type LIKE '%armour%'
            OR v_item_type LIKE '%shield%'
            OR v_item_type LIKE '%helmet%'
        ) THEN
            RAISE EXCEPTION 'Only weapons, armor, shields, and helmets can receive this improvement.';
        END IF;

        v_price := ROUND(
            GREATEST(25.00,GREATEST(0.01,COALESCE(p_base_value_gp,0.01))*0.40)
            * v_shop.settlement_multiplier
            * public.discord_economy_buy_reputation_multiplier(v_rep),2);

        v_remaining_gold := public.discord_adjust_currency_value(
            v_character.character_id,p_campaign_id,-v_price);

        UPDATE public.discord_inventory_items
        SET item_data = COALESCE(item_data,'{}'::jsonb) || jsonb_build_object(
                'economy_improvement_level',1,
                'economy_improvement_name','Masterwork +1',
                'economy_improved_at',NOW()),
            notes = TRIM(BOTH ' ' FROM COALESCE(notes,'') || ' Masterwork +1 improvement.'),
            updated_at = NOW()
        WHERE inventory_item_id = p_inventory_item_id;

        UPDATE public.discord_economy_shops
        SET wealth_gp = LEAST(wealth_cap_gp * 1.50,ROUND(wealth_gp + v_price,2)),
            updated_at = NOW()
        WHERE shop_id = v_shop.shop_id;

        INSERT INTO public.discord_economy_transactions(
            campaign_id,shop_id,character_id,transaction_kind,item_name,quantity,
            unit_price_gp,total_gp,details)
        VALUES(
            p_campaign_id,v_shop.shop_id,v_character.character_id,'improve',v_inventory.item_name,1,
            v_price,v_price,jsonb_build_object('improvement','Masterwork +1','itemType',p_item_type));

        RETURN jsonb_build_object(
            'success',TRUE,
            'serviceType','improve',
            'itemName',v_inventory.item_name,
            'priceGp',v_price,
            'remainingGold',v_remaining_gold,
            'message',v_inventory.item_name || ' upgraded to Masterwork +1.'
        );
    END IF;

    RAISE EXCEPTION 'Unknown blacksmith service.';
END;
$$;

DROP FUNCTION IF EXISTS public.discord_economy_claim_order(UUID,UUID,UUID);
CREATE OR REPLACE FUNCTION public.discord_economy_claim_order(
    p_player_id UUID,
    p_campaign_id UUID,
    p_order_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_active_player UUID;
    v_character RECORD;
    v_order public.discord_blacksmith_orders%ROWTYPE;
    v_shop public.discord_economy_shops%ROWTYPE;
    v_inventory_id UUID;
BEGIN
    IF NOT EXISTS(
        SELECT 1 FROM public.discord_campaign_members m
        WHERE m.campaign_id = p_campaign_id AND m.player_id = p_player_id
    ) THEN RAISE EXCEPTION 'You are not a member of this campaign.'; END IF;

    v_active_player := public.discord_resolve_active_player(p_player_id,p_campaign_id);
    SELECT c.* INTO v_character
    FROM public.discord_characters c
    WHERE c.campaign_id = p_campaign_id AND c.player_id = v_active_player
    LIMIT 1;
    IF v_character.character_id IS NULL THEN
        RAISE EXCEPTION 'Active campaign character could not be found.';
    END IF;

    SELECT * INTO v_order
    FROM public.discord_blacksmith_orders
    WHERE order_id = p_order_id
      AND campaign_id = p_campaign_id
      AND character_id = v_character.character_id
    FOR UPDATE;
    IF v_order.order_id IS NULL THEN
        RAISE EXCEPTION 'Commission order could not be found.';
    END IF;

    SELECT * INTO v_shop
    FROM public.discord_economy_shops
    WHERE shop_id = v_order.shop_id;
    IF v_shop.shop_id IS NULL THEN
        RAISE EXCEPTION 'Commissioning shop could not be found.';
    END IF;

    IF NOT EXISTS(
        SELECT 1 FROM public.discord_player_settlement_locations l
        WHERE l.campaign_id = p_campaign_id
          AND l.player_id = p_player_id
          AND LOWER(l.settlement_key) = LOWER(v_shop.settlement_key)
          AND LOWER(l.poi_key) = LOWER(v_shop.poi_key)
    ) THEN
        RAISE EXCEPTION 'Return to the commissioning shop to claim this item.';
    END IF;

    IF v_order.status = 'completed' THEN
        RAISE EXCEPTION 'This commission has already been claimed.';
    END IF;
    IF v_order.status = 'cancelled' THEN
        RAISE EXCEPTION 'This commission was cancelled.';
    END IF;
    IF v_order.ready_at > NOW() THEN
        RAISE EXCEPTION 'This commission is not ready yet.';
    END IF;

    PERFORM public.discord_gm_add_inventory_item(
        v_character.character_id,
        p_campaign_id,
        v_order.item_name,
        1,
        v_order.item_description,
        'Commissioned from ' || v_shop.shop_name,
        'Build 6.29 commissioned equipment');

    SELECT i.inventory_item_id INTO v_inventory_id
    FROM public.discord_inventory_items i
    WHERE i.character_id = v_character.character_id
      AND LOWER(TRIM(i.item_name)) = LOWER(TRIM(v_order.item_name))
    ORDER BY i.updated_at DESC,i.created_at DESC,i.inventory_item_id DESC
    LIMIT 1;

    IF v_inventory_id IS NOT NULL AND v_order.item_data <> '{}'::jsonb THEN
        UPDATE public.discord_inventory_items
        SET item_data = COALESCE(item_data,'{}'::jsonb) || v_order.item_data,
            updated_at = NOW()
        WHERE inventory_item_id = v_inventory_id;
    END IF;

    UPDATE public.discord_blacksmith_orders
    SET status = 'completed',
        completed_at = NOW()
    WHERE order_id = v_order.order_id;

    INSERT INTO public.discord_economy_transactions(
        campaign_id,shop_id,character_id,transaction_kind,item_name,quantity,
        unit_price_gp,total_gp,details)
    VALUES(
        p_campaign_id,v_shop.shop_id,v_character.character_id,'claim_commission',
        v_order.item_name,1,0,0,jsonb_build_object('orderId',v_order.order_id));

    RETURN jsonb_build_object(
        'success',TRUE,
        'orderId',v_order.order_id,
        'itemName',v_order.item_name,
        'message','Commission claimed: ' || v_order.item_name || '.'
    );
END;
$$;

-- Future durability/combat systems can call this service-role-only hook. Build
-- 6.29 deliberately does not introduce automatic combat wear by itself.
DROP FUNCTION IF EXISTS public.discord_economy_set_item_condition(UUID,INTEGER);
CREATE OR REPLACE FUNCTION public.discord_economy_set_item_condition(
    p_inventory_item_id UUID,
    p_condition_percent INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT EXISTS(
        SELECT 1 FROM public.discord_inventory_items i
        WHERE i.inventory_item_id = p_inventory_item_id
    ) THEN
        RAISE EXCEPTION 'Inventory item could not be found.';
    END IF;

    INSERT INTO public.discord_item_condition(inventory_item_id,condition_percent)
    VALUES(p_inventory_item_id,GREATEST(0,LEAST(100,COALESCE(p_condition_percent,100))))
    ON CONFLICT(inventory_item_id) DO UPDATE
    SET condition_percent = EXCLUDED.condition_percent,
        updated_at = NOW();
END;
$$;

-- Lock all Build 6.29 functions away from direct browser/authenticated access.
REVOKE ALL ON FUNCTION public.discord_economy_settlement_multiplier(TEXT) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_wealth_cap(TEXT,NUMERIC) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_reputation_score(UUID,UUID) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_reputation_label(INTEGER) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_buy_reputation_multiplier(INTEGER) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_sell_reputation_multiplier(INTEGER) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_scarcity_multiplier(INTEGER,INTEGER) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_condition_multiplier(INTEGER) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_material_demand_multiplier(TEXT,TEXT) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_refresh_shop(UUID) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_seed_shop(UUID,TEXT,TEXT,TEXT,TEXT,TEXT,JSONB) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_get_shop(UUID,UUID,UUID,JSONB,JSONB) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_buy(UUID,UUID,UUID,INTEGER) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_sell(UUID,UUID,UUID,INTEGER,BOOLEAN,TEXT,TEXT,TEXT,NUMERIC,TEXT,JSONB) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_blacksmith_service(UUID,UUID,TEXT,UUID,TEXT,TEXT,NUMERIC,UUID) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_claim_order(UUID,UUID,UUID) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.discord_economy_set_item_condition(UUID,INTEGER) FROM PUBLIC,anon,authenticated;

GRANT EXECUTE ON FUNCTION public.discord_economy_seed_shop(UUID,TEXT,TEXT,TEXT,TEXT,TEXT,JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_economy_get_shop(UUID,UUID,UUID,JSONB,JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_economy_buy(UUID,UUID,UUID,INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_economy_sell(UUID,UUID,UUID,INTEGER,BOOLEAN,TEXT,TEXT,TEXT,NUMERIC,TEXT,JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_economy_blacksmith_service(UUID,UUID,TEXT,UUID,TEXT,TEXT,NUMERIC,UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_economy_claim_order(UUID,UUID,UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.discord_economy_set_item_condition(UUID,INTEGER) TO service_role;

COMMENT ON TABLE public.discord_economy_shops IS
'Build 6.29 persistent settlement merchant state: market factor, available wealth, and restock clock.';
COMMENT ON TABLE public.discord_economy_stock IS
'Build 6.29 persistent finite merchant stock including player-sold resale merchandise.';
COMMENT ON TABLE public.discord_item_condition IS
'Build 6.29 optional persistent item condition used by resale and blacksmith repair services.';
COMMENT ON TABLE public.discord_blacksmith_orders IS
'Build 6.29 timed blacksmith commissions claimed at the originating merchant.';
COMMENT ON FUNCTION public.discord_economy_set_item_condition(UUID,INTEGER) IS
'Build 6.29 service-role durability hook. This build itself does not automatically damage equipment.';

NOTIFY pgrst,'reload schema';

COMMIT;
